// Travelify — trip-fit matcher.
// Flow: pick a city -> pick a hotel in it -> pick a trip theme -> get a
// fit score + reasons for why that hotel suits that theme.
//
// Keeps a Trip Journal of past results — one mechanic borrowed deliberately
// from why Beli got trendy (research notes, not folklore): it frames each
// result as a personal travel memory rather than a one-off lookup (Beli
// succeeded partly by being a memory archive, not a review site). Beli's
// other big lever — peer trust over anonymous reviews — doesn't translate
// here: this is a solo planning tool with no social graph, so it's left
// out rather than faked with fabricated "friends."
//
// The fit score is a transparent rule-based heuristic over each hotel's
// own tags/tier (see data.js) — not a live AI/LLM call.

const STORAGE_KEY = "hotelify_tripmatch_v1";
const THEME_KEYS = ["romantic", "family", "business", "adventure", "relaxation"];

// Simple modern mark: a white map pin on a rounded green tile.
const LOGO_GREEN = "#2e7d4f";
const LOGO_PIN_PATH = "M16 6.2c-3.7 0-6.7 2.9-6.7 6.6 0 4.8 6.7 12.9 6.7 12.9s6.7-8.1 6.7-12.9c0-3.7-3-6.6-6.7-6.6z";
const LOGO_SVG = `
  <svg width="30" height="30" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <rect width="32" height="32" rx="9" fill="${LOGO_GREEN}"/>
    <path d="${LOGO_PIN_PATH}" fill="#fff"/>
    <circle cx="16" cy="12.8" r="2.7" fill="${LOGO_GREEN}"/>
  </svg>
`;

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    return {
      journal: parsed.journal || [],
    };
  } catch (e) {
    return { journal: [] };
  }
}

function saveState() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}

let state = loadState();
let step = "city"; // city | hotel | theme | answer | journal
let cityQuery = "";
let selectedCity = null;
let selectedHotel = null;
let selectedTheme = null;
let showCustomHotelForm = false;
let showAllCities = false;
let answerTab = "hotel"; // hotel | plan
let shareOpen = false;
let suggestedPlaces = null; // null = the hotel's own nearby list
let suggestionsLoading = false;
let suggestionsError = null;
let seenSuggestions = new Set();

// AI plan check (Gemini) — the only place this app calls an LLM. The API
// key lives ONLY in localStorage, entered by the user at runtime in this
// running page — never written into a source file, so it never ends up
// in a git commit. If this app is ever hosted somewhere other than your
// own machine, anyone with dev tools open on that page could still read
// the key out of the request, same as any client-side API call — keep
// that in mind before deploying it publicly with a real key attached.
const GEMINI_KEY_STORAGE = "hotelify_gemini_key";
const GEMINI_MODEL = "gemini-3.8-flash";

// Customer-built day-by-day itinerary, checked for logistics (walking
// distance, traffic, pacing) by AI rather than generated by it. Customers
// add/remove days freely — no fixed cap.
let planCheckDays = [[]];
let planCheckNotes = "";
let planCheckLoading = false;
let planCheckError = null;
let planCheckResult = null;
// How the traveler wants to get between stops: "auto" | "transit" | "taxi".
let planTransport = "auto";

// ---------- accounts (Supabase) ----------
// Falls back to the existing guest/localStorage journal untouched when
// config.js still has placeholder values (see auth.js).
let currentUser = null;
let journalSource = "guest"; // "guest" | "account"
let authError = null;
let authLoading = false;

// Sharing a checked plan (stops + notes) publicly to the community feed.
let sharePlanLoading = false;
let sharePlanError = null;
let sharePlanSuccess = false;
let communityPlans = [];
let communityLoading = false;
let communityError = null;
let communityView = "latest"; // latest | plans | creators
let rankingLoading = false;
let rankingError = null;
let ranking = { plans: [], creators: [], myRank: null, myLikes: 0 };
const RECENT_DAYS = 30;
let communityEngagementError = null;
let planVotes = {}; // planId -> { up, down, mine: 1 | -1 | 0 }
let planComments = {}; // planId -> [comment rows]
let expandedComments = new Set();
let commentDrafts = {};

// Following + Feed (public journals of people you follow).
let followingIds = new Set();
let followNames = {}; // userId -> username
let followError = null;
let feedEntries = [];
let feedLoading = false;
let feedError = null;
let journalPublic = null; // null = unknown / not loaded
let journalPublicError = null;

async function initAuth() {
  if (!isSupabaseConfigured()) return;
  currentUser = await getCurrentUser();
  if (currentUser) {
    await loadAccountJournal();
    await loadSocial();
  }
  render();
  supabaseClient.auth.onAuthStateChange(async (_event, session) => {
    currentUser = session ? session.user : null;
    if (currentUser) {
      await loadAccountJournal();
      await loadSocial();
    } else {
      journalSource = "guest";
      state = loadState();
      resetSocial();
    }
    render();
  });
}

async function loadAccountJournal() {
  try {
    state.journal = await fetchJournalEntries(currentUser.id);
    journalSource = "account";
  } catch (e) {
    console.error("Failed to load account journal", e);
  }
}

function resetSocial() {
  followingIds = new Set();
  followNames = {};
  feedEntries = [];
  feedError = null;
  followError = null;
  journalPublic = null;
  journalPublicError = null;
}

// Who I follow and whether my own journal is public. Failures (e.g. the
// database update hasn't been run yet) are shown where they matter.
async function loadSocial() {
  try {
    followingIds = new Set(await fetchFollowing(currentUser.id));
    const profiles = await fetchProfiles([...followingIds]);
    profiles.forEach((p) => (followNames[p.id] = p.username));
  } catch (e) {
    console.error("Failed to load following", e);
  }
  try {
    const profile = await fetchMyProfile(currentUser.id);
    journalPublic = !!(profile && profile.journal_public);
    journalPublicError = null;
  } catch (e) {
    journalPublic = null;
    journalPublicError = "Public journals need a database update — run the latest supabase/schema.sql in your Supabase SQL Editor.";
  }
}

async function toggleFollow(userId, username) {
  if (!currentUser) {
    openAuthModal("signin");
    return;
  }
  const was = followingIds.has(userId);
  if (was) followingIds.delete(userId);
  else {
    followingIds.add(userId);
    if (username) followNames[userId] = username;
  }
  followError = null;
  render();
  try {
    if (was) await unfollowUser(currentUser.id, userId);
    else await followUser(currentUser.id, userId);
    if (step === "feed") await loadFeed();
  } catch (e) {
    if (was) followingIds.add(userId);
    else followingIds.delete(userId);
    followError = "Couldn't update follow. Try again.";
    render();
  }
}

async function viewFeed() {
  step = "feed";
  render();
  if (!currentUser) return;
  if (!communityPlans.length) {
    try {
      communityPlans = await fetchPublicPlans(50);
    } catch (e) {
      // suggestions are optional
    }
  }
  await loadFeed();
}

async function loadFeed() {
  if (!currentUser) return;
  feedLoading = true;
  feedError = null;
  render();
  try {
    const ids = [...followingIds];
    const [entries, profiles] = await Promise.all([fetchFeedEntries(ids, 60), fetchProfiles(ids)]);
    profiles.forEach((p) => (followNames[p.id] = p.username));
    feedEntries = entries;
  } catch (e) {
    feedEntries = [];
    feedError = "Couldn't load the feed. If this keeps happening, run the latest supabase/schema.sql in your Supabase SQL Editor.";
  }
  feedLoading = false;
  render();
}

async function toggleJournalPublic() {
  if (!currentUser || journalPublic === null) return;
  const next = !journalPublic;
  journalPublic = next;
  render();
  try {
    await setJournalPublic(currentUser.id, next);
  } catch (e) {
    journalPublic = !next;
    journalPublicError = "Couldn't update your journal privacy. Try again.";
    render();
  }
}

// ---------- data helpers ----------

function uniqueCities() {
  return [...new Set(MOCK_HOTELS.map((h) => h.city))].sort();
}

function hotelsInCity(city) {
  const c = city.trim().toLowerCase();
  return MOCK_HOTELS.filter((h) => h.city.toLowerCase() === c);
}

function makeCustomId() {
  return "custom-" + Date.now() + "-" + Math.floor(Math.random() * 1000);
}

// Fallback only, for hotels with no known official site (custom/manual
// entries) — a general search rather than a fabricated booking link.
// Any hotel with a real `website` on file books there directly instead.
function hotelSearchFallbackUrl(h) {
  const query = encodeURIComponent([h.name, h.city, h.country].filter(Boolean).join(" "));
  return `https://www.google.com/travel/hotels?q=${query}`;
}

// Links to live Google Maps directions from the city's airport rather
// than a hardcoded fare/time — this app has no real transit-pricing API,
// so an invented "$12, 35 min" would just be a guess dressed up as fact.
// Google Maps computes current, real transit vs. driving estimates.
function gettingThereUrls(h) {
  const destination = encodeURIComponent(h.address || [h.name, h.city, h.country].filter(Boolean).join(", "));
  const origin = encodeURIComponent(`${h.city} airport`);
  return {
    transit: `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=transit`,
    driving: `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=driving`,
  };
}

// ---------- Gemini trip planning ----------

function getGeminiKey() {
  return localStorage.getItem(GEMINI_KEY_STORAGE) || "";
}

function setGeminiKey(key) {
  localStorage.setItem(GEMINI_KEY_STORAGE, key.trim());
}

function clearGeminiKey() {
  localStorage.removeItem(GEMINI_KEY_STORAGE);
}

// Static order used if the model list can't be fetched.
const GEMINI_FALLBACK_MODELS = [GEMINI_MODEL, "gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.1-flash-lite"];
let discoveredModels = null;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function modelRank(name) {
  const m = name.match(/gemini-(\d+(?:\.\d+)?)-flash(-lite)?/);
  if (!m) return -1;
  return parseFloat(m[1]) * 10 - (m[2] ? 0.5 : 0);
}

// Asks Google which models this key can actually call, so the app tries
// real models (newest first, lite variants after full ones) instead of
// guessing names. Cached for the page session.
async function getCandidateModels(key) {
  if (discoveredModels) return discoveredModels;
  try {
    const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?pageSize=200&key=${encodeURIComponent(key)}`);
    if (res.ok) {
      const data = await res.json();
      const names = (data.models || [])
        .filter((m) => (m.supportedGenerationMethods || []).includes("generateContent"))
        .map((m) => m.name.replace(/^models\//, ""))
        .filter((n) => /^gemini-\d+(\.\d+)?-flash(-lite)?$/.test(n))
        .sort((a, b) => modelRank(b) - modelRank(a));
      if (names.length) return (discoveredModels = names.slice(0, 6));
    }
  } catch (e) {
    // fall back to the static list
  }
  return GEMINI_FALLBACK_MODELS;
}

// One request to one model. Rejects with err.status set on failure.
async function requestModel(model, key, payload) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    const err = new Error(body && body.error && body.error.message ? body.error.message : `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.map((p) => p.text).join("") || "";
  if (!text) throw new Error("The AI returned an empty response.");
  return text.trim();
}

// Starts the first model right away and the next ones every couple of
// seconds without waiting for the earlier ones to fail; the first success
// wins. Overloaded models are slow to say no, so this is much faster than
// trying them one after another.
function raceModels(models, key, payload) {
  return new Promise((resolve, reject) => {
    let done = false;
    let failures = 0;
    let overloadError = null;
    let otherError = null;
    models.forEach((model, i) => {
      sleep(i * 1500)
        .then(() => (done ? null : requestModel(model, key, payload)))
        .then((text) => {
          if (text && !done) {
            done = true;
            resolve(text);
          }
        })
        .catch((err) => {
          if (done) return;
          if ([401, 403].includes(err.status)) {
            done = true;
            reject(err);
            return;
          }
          if ([503, 429, 404].includes(err.status)) overloadError = overloadError || err;
          else otherError = otherError || err;
          if (++failures === models.length) {
            done = true;
            reject(overloadError && !otherError ? Object.assign(new Error("overloaded"), { status: 503 }) : otherError || overloadError);
          }
        });
    });
  });
}

async function callGemini(prompt, { json = false } = {}) {
  const key = getGeminiKey();
  const payload = { contents: [{ parts: [{ text: prompt }] }] };
  if (json) payload.generationConfig = { responseMimeType: "application/json" };
  const models = await getCandidateModels(key);

  // Two rounds: if every model is overloaded, pause briefly and try again.
  for (let round = 0; round < 2; round++) {
    try {
      return await raceModels(models, key, payload);
    } catch (err) {
      if (err.status !== 503) throw err;
      if (round === 0) await sleep(3000);
    }
  }
  throw new Error("Google's AI is very busy right now, and every model we tried was overloaded. Please try again in a minute.");
}

// Reviews a customer-WRITTEN day-by-day stop list for logistics problems
// (too much walking/backtracking, likely bad traffic between far-apart
// stops, an overpacked or too-sparse day) and estimates calories burned
// per day from the walking it implies — this app's only AI call.
async function evaluateCustomItinerary(hotel, themeKey, days) {
  const theme = THEME_META[themeKey];
  const dayLines = days
    .map((stops, i) => `Day ${i + 1}: ${stops.length ? stops.join(" -> ") : "(no stops added)"}`)
    .join("\n");
  const transportRule =
    planTransport === "transit"
      ? "The traveler wants to use public transit (subway, metro, bus, train) for any leg too far to walk. Assume transit wherever it exists in this city; only mention a car where transit truly isn't available."
      : planTransport === "taxi"
      ? "The traveler prefers taxi/rideshare for any leg too far to walk. Assume taxi times and fares. EXCEPTION: in New York City (and other cities where the subway or metro is clearly faster, such as Washington DC, London, Paris, Tokyo), do NOT recommend a taxi — traffic makes it slow and costly. For those legs, say the subway/metro is faster and cheaper, give its time and cost instead, and mark the leg \"review\"."
      : "No preference: pick the most sensible mode per leg for this city (see guidance above).";
  const prompt = `You are a practical, concise travel-logistics reviewer, not a trip planner. A traveler staying at ${hotel.name} in ${hotel.city}${hotel.country ? ", " + hotel.country : ""} on a ${theme.label}-themed trip has drafted this day-by-day list of places they want to visit, in the order listed:\n${dayLines}\n\nGive feedback on EVERY stop and on EVERY leg between consecutive stops (a leg is the trip from one stop to the next, in order).\n- For each stop: a verdict, a short feedback line, and 1-3 keywords describing it (pick from words like luxurious, fun, budget-friendly, romantic, historic, scenic, relaxing, foodie, cultural, active, shopping, nightlife, family-friendly, touristy, crowded — or another short fitting word).\n- For each leg: a verdict and feedback covering distance, the best way to get between the two stops, and likely traffic. Do NOT default to taxi. Pick the most sensible mode for THIS city and distance: walking for nearby stops; public transit (subway, metro, bus, train) in cities where it's fast, reliable and safe for visitors, such as New York, Washington DC, London, Paris, Tokyo, Singapore, Hong Kong, Berlin, Boston, Chicago; and rideshare/taxi/driving only where transit is poor, slow, or has real safety concerns for visitors, such as Los Angeles. When both transit and a car are reasonable, mention both briefly with rough times. Name the specific line or mode when you know it. Never recommend a taxi or rideshare in New York City. TRANSPORT PREFERENCE: ${transportRule}\n- Also for each leg give "mode" (the ONE mode you assumed: walk, subway, bus, train, taxi or car), "minutes" (realistic door-to-door travel time as a number) and "cost" (rough per-person cost in USD as a short string such as "$3" or "$14"; use "free" for walking).\n- For each day, also judge the ORDER of its stops. If a different order would cut backtracking, walking or traffic, or suit time of day (e.g. morning-only markets or museums first, sunset viewpoints and nightlife last), set "betterOrder" to the SAME stop names, spelled exactly as given, in the better sequence, and "orderNote" to a short reason (under 25 words). If the current order already works, set "betterOrder" to null and "orderNote" to a very short confirmation. Never add, drop or rename stops in betterOrder.
- For each day: estimated total walking distance (km) and calories burned (kcal) for an average adult, assuming they walk between nearby stops and use the transport described above for far-apart ones (rough estimates). Also give the day's total travel time ("travelMinutes", number, all legs combined) and total transport cost ("travelCost", short USD string such as "$9" or "free").\n\nKeep feedback SHORT (under 15 words) when something is fine. Use up to ~40 words only when a change is needed, and say specifically what to change (reorder, drop, split the day, switch transport mode). Don't invent problems.\n\nRespond with ONLY a JSON object of exactly this shape. "days" has one entry per day in order (${days.length} total); each day's "stops" has one entry per stop in order, and "legs" has one entry per consecutive pair (stops minus one; empty array if 0 or 1 stops):\n{"days":[{"stops":[{"verdict":"good" or "review","feedback":"...","keywords":["..."]}],"legs":[{"verdict":"good" or "review","feedback":"...","mode":"walk|subway|bus|train|taxi|car","minutes":number,"cost":"$3"}],"betterOrder":["stop names"] or null,"orderNote":"...","walkingKm":number,"kcal":number,"travelMinutes":number,"travelCost":"$9"}],"summary":"1-2 sentence overall take","keywords":["2-4 keywords describing the whole plan"],"totalKcal":number,"totalTravelCost":"$27"}\nUse "good" when it works as written and "review" when it's worth looking at again.`;
  const text = await callGemini(prompt, { json: true });
  try {
    const parsed = JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g, ""));
    if (parsed && Array.isArray(parsed.days)) return parsed;
  } catch (e) {
    // fall through to raw text
  }
  return { raw: text };
}

function hotelSubtitle(h) {
  return [h.city, h.country].filter(Boolean).join(", ");
}

// ---------- fit scoring ----------

function evaluateFit(hotel, themeKey) {
  const theme = THEME_META[themeKey];
  const tags = hotel.tags || [];
  const matchedTags = tags.filter((t) => theme.tags.includes(t));
  let score = 45 + matchedTags.length * 13;
  const tierMatch = hotel.tier && theme.tierBoost.includes(hotel.tier);
  if (tierMatch) score += 12;
  score = Math.max(5, Math.min(98, Math.round(score)));

  const reasons = matchedTags.map((t) => theme.tagReasons[t]).filter(Boolean);
  if (tierMatch) {
    reasons.push(`a ${TIER_META[hotel.tier].label.toLowerCase()} property, well suited to a ${theme.label.toLowerCase()} trip`);
  }
  if (reasons.length === 0) {
    reasons.push(
      `no specific ${theme.label.toLowerCase()}-oriented details on file for this hotel, so this is a lower-confidence match`
    );
  }

  const verdict = score >= 75 ? "Great match" : score >= 50 ? "Decent match" : "Not an ideal match";
  const color = score >= 75 ? "#2e7d4f" : score >= 50 ? "#b8860b" : "#c0392b";
  return { score, reasons: reasons.slice(0, 4), verdict, color };
}

// ---------- badges ----------
// Self-paced achievements computed from journal history — work the same
// whether the journal is guest/localStorage or account-synced, since
// they only read already-loaded `state.journal` fields.

const BADGE_DEFS = [
  { id: "first-trip", emoji: "🧳", label: "First Trip", description: "Matched your first hotel.", check: (s) => s.total >= 1 },
  { id: "city-hopper", emoji: "🗺️", label: "City Hopper", description: "Matched hotels in 5+ cities.", check: (s) => s.cityCount >= 5 },
  { id: "world-explorer", emoji: "🌍", label: "World Explorer", description: "Matched hotels in 15+ cities.", check: (s) => s.cityCount >= 15 },
  { id: "perfect-match", emoji: "🎯", label: "Perfect Match", description: "Scored a 90%+ fit.", check: (s) => s.maxScore >= 90 },
  { id: "romantic", emoji: "💕", label: "Hopeless Romantic", description: "3+ Romantic trip matches.", check: (s) => (s.themeCounts.romantic || 0) >= 3 },
  { id: "family", emoji: "👨‍👩‍👧", label: "Family Planner", description: "3+ Family trip matches.", check: (s) => (s.themeCounts.family || 0) >= 3 },
  { id: "business", emoji: "💼", label: "Road Warrior", description: "3+ Business trip matches.", check: (s) => (s.themeCounts.business || 0) >= 3 },
  { id: "adventure", emoji: "🧗", label: "Thrill Seeker", description: "3+ Adventure trip matches.", check: (s) => (s.themeCounts.adventure || 0) >= 3 },
  { id: "relaxation", emoji: "🧘", label: "Zen Master", description: "3+ Relaxation trip matches.", check: (s) => (s.themeCounts.relaxation || 0) >= 3 },
  { id: "decade-club", emoji: "📅", label: "Decade Club", description: "10+ trips matched total.", check: (s) => s.total >= 10 },
];

function computeJournalStats(journal) {
  const cities = new Set(journal.map((j) => j.city));
  const themeCounts = {};
  let maxScore = 0;
  journal.forEach((j) => {
    themeCounts[j.themeKey] = (themeCounts[j.themeKey] || 0) + 1;
    if (j.score > maxScore) maxScore = j.score;
  });
  return { total: journal.length, cityCount: cities.size, themeCounts, maxScore };
}

function computeEarnedBadges(journal) {
  const stats = computeJournalStats(journal);
  return BADGE_DEFS.map((b) => ({ ...b, earned: b.check(stats) }));
}

// ---------- journal ----------

function recordTripMatch(entry) {
  // Re-matching the same hotel + vibe refreshes the existing entry instead
  // of adding a duplicate row (which also inflated badge counts).
  const existing = state.journal.findIndex((j) => j.themeKey === entry.themeKey && (entry.hotelId ? j.hotelId === entry.hotelId : j.hotelName === entry.hotelName));
  if (existing !== -1) {
    const [prev] = state.journal.splice(existing, 1);
    state.journal.unshift({ ...prev, score: entry.score, verdict: entry.verdict, timestamp: entry.timestamp });
    if (!(journalSource === "account" && currentUser)) saveState();
    return;
  }
  state.journal.unshift(entry);
  if (journalSource === "account" && currentUser) {
    insertJournalEntry(currentUser.id, entry).catch((e) => {
      console.error("Failed to sync journal entry to account", e);
    });
  } else {
    saveState();
  }
}

// ---------- session (keeps your place if the page reloads) ----------

const SESSION_KEY = "hotelify_session_v1";

function saveSession() {
  try {
    localStorage.setItem(
      SESSION_KEY,
      JSON.stringify({ selectedCity, selectedTheme, selectedHotel, step: ["city", "theme", "hotel", "answer"].includes(step) ? step : planStep(), answerTab, planCheckDays, planCheckNotes, planCheckResult, planTransport })
    );
  } catch (e) {
    // storage unavailable — progress just won't persist
  }
}

function restoreSession() {
  try {
    const saved = JSON.parse(localStorage.getItem(SESSION_KEY) || "null");
    if (!saved) return;
    selectedCity = saved.selectedCity || null;
    selectedTheme = saved.selectedTheme && THEME_META[saved.selectedTheme] ? saved.selectedTheme : null;
    selectedHotel = saved.selectedHotel || null;
    answerTab = saved.answerTab === "plan" ? "plan" : "hotel";
    if (Array.isArray(saved.planCheckDays) && saved.planCheckDays.length) planCheckDays = saved.planCheckDays;
    planCheckNotes = saved.planCheckNotes || "";
    planCheckResult = saved.planCheckResult || null;
    planTransport = ["auto", "transit", "taxi"].includes(saved.planTransport) ? saved.planTransport : "auto";
    step = planStep();
  } catch (e) {
    // ignore a corrupt saved session
  }
}

// ---------- trip photos ----------
// After a trip, travelers can attach photos to each stop of their plan.
// Photos are resized in the browser and kept only on this device
// (IndexedDB), grouped by hotel + stop name so they survive reloads and
// come back if the same stop is added again.

const PHOTO_DB = "travelify_photos";
const PHOTO_STORE = "photos";
const MAX_PHOTOS_PER_STOP = 12;
let photoCache = {}; // stopKey -> [{ id, thumbUrl }]
let photoNotice = null;

function openPhotoDb() {
  return new Promise((resolve, reject) => {
    if (!window.indexedDB) return reject(new Error("IndexedDB unavailable"));
    const req = indexedDB.open(PHOTO_DB, 1);
    req.onupgradeneeded = () => {
      const store = req.result.createObjectStore(PHOTO_STORE, { keyPath: "id" });
      store.createIndex("hotelId", "hotelId");
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function photoDbRequest(mode, fn) {
  return openPhotoDb().then(
    (db) =>
      new Promise((resolve, reject) => {
        const tx = db.transaction(PHOTO_STORE, mode);
        const req = fn(tx.objectStore(PHOTO_STORE));
        tx.oncomplete = () => {
          db.close();
          resolve(req && req.result);
        };
        tx.onerror = tx.onabort = () => {
          db.close();
          reject(tx.error);
        };
      })
  );
}

function photoHotelKey() {
  return selectedHotel ? String(selectedHotel.id || selectedHotel.name) : null;
}

function stopPhotoKey(name) {
  return String(name).trim().toLowerCase();
}

// Reloads the thumbnails for the current hotel (and clears them when there isn't one).
async function loadHotelPhotos() {
  Object.values(photoCache).forEach((list) => list.forEach((p) => URL.revokeObjectURL(p.thumbUrl)));
  photoCache = {};
  const hotelKey = photoHotelKey();
  if (!hotelKey) return;
  try {
    const rows = await photoDbRequest("readonly", (store) => store.index("hotelId").getAll(hotelKey));
    if (hotelKey !== photoHotelKey()) return; // hotel changed while loading
    rows.sort((a, b) => a.createdAt - b.createdAt);
    rows.forEach((r) => {
      (photoCache[r.stopKey] = photoCache[r.stopKey] || []).push({ id: r.id, thumbUrl: URL.createObjectURL(r.thumb) });
    });
    render();
  } catch (e) {
    // storage unavailable — photos just won't persist
  }
}

function resizeToBlob(bitmap, maxSide, quality) {
  const scale = Math.min(1, maxSide / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement("canvas");
  canvas.width = Math.max(1, Math.round(bitmap.width * scale));
  canvas.height = Math.max(1, Math.round(bitmap.height * scale));
  canvas.getContext("2d").drawImage(bitmap, 0, 0, canvas.width, canvas.height);
  return new Promise((resolve, reject) =>
    canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error("encode failed"))), "image/jpeg", quality)
  );
}

async function processPhotoFile(file) {
  const bitmap = await createImageBitmap(file);
  try {
    return { full: await resizeToBlob(bitmap, 1600, 0.82), thumb: await resizeToBlob(bitmap, 360, 0.75) };
  } finally {
    if (bitmap.close) bitmap.close();
  }
}

async function addStopPhotos(stopName, fileList) {
  const hotelKey = photoHotelKey();
  if (!hotelKey) return;
  const files = Array.from(fileList).filter((f) => f.type.startsWith("image/"));
  const key = stopPhotoKey(stopName);
  const room = Math.max(0, MAX_PHOTOS_PER_STOP - (photoCache[key] || []).length);
  const picked = files.slice(0, room);
  let failed = 0;
  for (const file of picked) {
    try {
      const { full, thumb } = await processPhotoFile(file);
      const rec = { id: "ph-" + Date.now() + "-" + Math.random().toString(36).slice(2, 8), hotelId: hotelKey, stopKey: key, full, thumb, createdAt: Date.now() };
      await photoDbRequest("readwrite", (store) => store.put(rec));
      if (hotelKey !== photoHotelKey()) return;
      (photoCache[key] = photoCache[key] || []).push({ id: rec.id, thumbUrl: URL.createObjectURL(thumb) });
    } catch (e) {
      failed++;
    }
  }
  const notes = [];
  if (files.length > picked.length) notes.push(`Up to ${MAX_PHOTOS_PER_STOP} photos per stop.`);
  if (failed) notes.push(`${failed} photo${failed > 1 ? "s" : ""} couldn't be added (unsupported format or storage full).`);
  photoNotice = notes.length ? notes.join(" ") : null;
  render();
}

async function removeStopPhoto(photoId) {
  try {
    await photoDbRequest("readwrite", (store) => store.delete(photoId));
  } catch (e) {
    return;
  }
  Object.keys(photoCache).forEach((key) => {
    photoCache[key] = photoCache[key].filter((p) => {
      if (p.id !== photoId) return true;
      URL.revokeObjectURL(p.thumbUrl);
      return false;
    });
    if (!photoCache[key].length) delete photoCache[key];
  });
  render();
}

async function openPhotoLightbox(photoId) {
  let rec;
  try {
    rec = await photoDbRequest("readonly", (store) => store.get(photoId));
  } catch (e) {
    return;
  }
  if (!rec) return;
  const url = URL.createObjectURL(rec.full);
  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";
  overlay.innerHTML = `
    <div class="share-modal photo-lightbox">
      <button class="icon-btn share-modal-close" id="photo-close">✕ Close</button>
      <div class="share-canvas-wrap"><img src="${url}" alt="Trip photo" /></div>
      <div class="share-modal-actions">
        <button class="pill-btn ghost" id="photo-delete">Delete photo</button>
      </div>
    </div>`;
  document.body.appendChild(overlay);
  const close = () => {
    URL.revokeObjectURL(url);
    overlay.remove();
  };
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.getElementById("photo-close").addEventListener("click", close);
  document.getElementById("photo-delete").addEventListener("click", async () => {
    close();
    await removeStopPhoto(photoId);
  });
}

// ---------- navigation ----------

function chooseCity(city) {
  selectedCity = city;
  selectedHotel = null;
  showCustomHotelForm = false;
  step = "theme";
  render();
}

function chooseTheme(themeKey) {
  selectedTheme = themeKey;
  showCustomHotelForm = false;
  step = "hotel";
  render();
}

function chooseHotel(hotel, { record = true } = {}) {
  // Coming back to the same hotel + vibe keeps the plan you were building.
  const sameTrip = selectedHotel && selectedHotel.id === hotel.id;
  selectedHotel = hotel;
  answerTab = "hotel";
  if (!sameTrip) {
    resetSuggestions();
    shareOpen = false;
    sharePlanError = null;
    sharePlanSuccess = false;
    planCheckDays = [[]];
    planCheckNotes = "";
    planCheckResult = null;
    planCheckError = null;
    loadHotelPhotos();
  }
  const fit = evaluateFit(hotel, selectedTheme);
  if (record) recordTripMatch({
    id: "trip-" + Date.now(),
    hotelId: hotel.id,
    city: hotel.city,
    hotelName: hotel.name,
    themeKey: selectedTheme,
    score: fit.score,
    verdict: fit.verdict,
    timestamp: Date.now(),
  });
  step = "answer";
  render();
}

function planNewTrip() {
  resetSuggestions();
  answerTab = "hotel";
  shareOpen = false;
  showAllCities = false;
  selectedCity = null;
  selectedHotel = null;
  selectedTheme = null;
  cityQuery = "";
  showCustomHotelForm = false;
  sharePlanError = null;
  sharePlanSuccess = false;
  planCheckDays = [[]];
  planCheckNotes = "";
  planCheckResult = null;
  planCheckError = null;
  loadHotelPhotos();
  step = "city";
  render();
}

function formatPlanCheckForSharing() {
  const dayLines = planCheckDays
    .map((stops, i) => `Day ${i + 1}: ${stops.length ? stops.join(" -> ") : "(no stops added)"}`)
    .join("\n");
  const notes = planCheckNotes.trim();
  let aiCheck = "";
  if (planCheckResult && planCheckResult.raw) {
    aiCheck = planCheckResult.raw.trim();
  } else if (planCheckResult) {
    const tag = (v) => (v === "good" ? "looks good" : "worth another look");
    aiCheck = planCheckResult.days
      .map((d, i) => {
        const lines = [`Day ${i + 1} (~${d.walkingKm} km, ~${d.kcal} kcal)`];
        if (Array.isArray(d.betterOrder) && d.orderNote) lines.push(`  Order tip: ${d.betterOrder.join(" -> ")} (${d.orderNote})`);
        (d.stops || []).forEach((st, si) => {
          const kw = st.keywords && st.keywords.length ? ` [${st.keywords.join(", ")}]` : "";
          lines.push(`  ${planCheckDays[i] ? planCheckDays[i][si] : "Stop"}${kw} - ${tag(st.verdict)}: ${st.feedback}`);
          const leg = (d.legs || [])[si];
          if (leg && si < (d.stops || []).length - 1) lines.push(`    -> next: ${tag(leg.verdict)}: ${leg.feedback}`);
        });
        return lines.join("\n");
      })
      .join("\n");
    if (planCheckResult.keywords && planCheckResult.keywords.length) aiCheck += `\nPlan vibe: ${planCheckResult.keywords.join(", ")}`;
    if (planCheckResult.summary) aiCheck += `\n${planCheckResult.summary}`;
    if (planCheckResult.totalKcal) aiCheck += `\nTotal: ~${planCheckResult.totalKcal} kcal`;
  }
  let text = dayLines;
  if (notes) text += `\n\nNotes: ${notes}`;
  if (aiCheck) text += `\n\nAI Check: ${aiCheck}`;
  return text;
}

async function shareMyPlan() {
  if (!currentUser) {
    openAuthModal("signin");
    return;
  }
  const hasAnyStops = planCheckDays.some((d) => d.length > 0);
  if (!hasAnyStops) return;
  sharePlanLoading = true;
  sharePlanError = null;
  render();
  try {
    const fit = evaluateFit(selectedHotel, selectedTheme);
    const username = currentUser.user_metadata && currentUser.user_metadata.username ? currentUser.user_metadata.username : currentUser.email;
    await sharePlanPublicly(currentUser.id, username, {
      hotelName: selectedHotel.name,
      city: selectedHotel.city,
      themeKey: selectedTheme,
      score: fit.score,
      planText: formatPlanCheckForSharing(),
    });
    sharePlanSuccess = true;
  } catch (e) {
    sharePlanError = e.message || "Couldn't share your plan.";
  }
  sharePlanLoading = false;
  render();
}

async function viewCommunity() {
  step = "community";
  communityView = "latest";
  communityLoading = true;
  communityError = null;
  render();
  try {
    communityPlans = await fetchPublicPlans(50);
  } catch (e) {
    communityError = e.message || "Couldn't load community plans.";
  }
  communityLoading = false;
  render();
  await loadEngagement();
}

async function setCommunityView(view) {
  communityView = view;
  render();
  if (view !== "latest") await loadRanking();
}

// Ranks are computed in the browser from the public plans and their votes,
// so no extra database setup is needed beyond the likes tables.
async function loadRanking() {
  rankingLoading = true;
  rankingError = null;
  render();
  try {
    const [plans, votes] = await Promise.all([fetchPublicPlans(500), fetchAllVotes()]);
    const tally = {};
    plans.forEach((p) => (tally[p.id] = { up: 0, down: 0, mine: 0 }));
    votes.forEach((v) => {
      const t = tally[v.plan_id];
      if (!t) return;
      if (v.vote === 1) t.up++;
      else t.down++;
      if (currentUser && v.user_id === currentUser.id) t.mine = v.vote;
    });
    Object.assign(planVotes, tally);

    const cutoff = Date.now() - RECENT_DAYS * 86400000;
    const byLikes = (a, b) => tally[b.id].up - tally[a.id].up || tally[a.id].down - tally[b.id].down || new Date(b.created_at) - new Date(a.created_at);
    const topPlans = plans.filter((p) => new Date(p.created_at).getTime() >= cutoff && tally[p.id].up > 0).sort(byLikes).slice(0, 10);

    const byUser = {};
    plans.forEach((p) => {
      const u = byUser[p.user_id] || (byUser[p.user_id] = { user_id: p.user_id, username: p.username, likes: 0, plans: 0, best: null });
      u.plans++;
      u.likes += tally[p.id].up;
      if (!u.best || tally[p.id].up > tally[u.best.id].up) u.best = p;
    });
    const sorted = Object.values(byUser).filter((u) => u.likes > 0).sort((a, b) => b.likes - a.likes || b.plans - a.plans);
    const myIdx = currentUser ? sorted.findIndex((u) => u.user_id === currentUser.id) : -1;
    ranking = { plans: topPlans, creators: sorted.slice(0, 10), myRank: myIdx === -1 ? null : myIdx + 1, myLikes: myIdx === -1 ? 0 : sorted[myIdx].likes };

    try {
      const { comments } = await fetchPlanEngagement(topPlans.map((p) => p.id));
      topPlans.forEach((p) => (planComments[p.id] = []));
      comments.forEach((c) => planComments[c.plan_id] && planComments[c.plan_id].push(c));
    } catch (e) {
      // comments are optional on the ranking view
    }
  } catch (e) {
    rankingError = "Rankings need the likes tables — run the latest supabase/schema.sql in your Supabase SQL Editor.";
  }
  rankingLoading = false;
  render();
}

async function loadEngagement() {
  communityEngagementError = null;
  try {
    const { votes, comments } = await fetchPlanEngagement(communityPlans.map((p) => p.id));
    planVotes = {};
    planComments = {};
    communityPlans.forEach((p) => {
      planVotes[p.id] = { up: 0, down: 0, mine: 0 };
      planComments[p.id] = [];
    });
    votes.forEach((v) => {
      const t = planVotes[v.plan_id];
      if (!t) return;
      if (v.vote === 1) t.up++;
      else t.down++;
      if (currentUser && v.user_id === currentUser.id) t.mine = v.vote;
    });
    comments.forEach((c) => {
      if (planComments[c.plan_id]) planComments[c.plan_id].push(c);
    });
  } catch (e) {
    communityEngagementError = "Likes and comments aren't set up yet — run the latest supabase/schema.sql in your Supabase SQL Editor.";
  }
  render();
}

async function voteOnPlan(planId, vote) {
  if (!currentUser) {
    openAuthModal("signin");
    return;
  }
  const t = planVotes[planId] || (planVotes[planId] = { up: 0, down: 0, mine: 0 });
  const prev = t.mine;
  if (prev === 1) t.up--;
  if (prev === -1) t.down--;
  t.mine = prev === vote ? 0 : vote;
  if (t.mine === 1) t.up++;
  if (t.mine === -1) t.down++;
  render();
  try {
    if (t.mine === 0) await clearPlanVote(currentUser.id, planId);
    else await setPlanVote(currentUser.id, planId, t.mine);
  } catch (e) {
    await loadEngagement();
  }
}

async function postComment(planId) {
  if (!currentUser) {
    openAuthModal("signin");
    return;
  }
  const body = (commentDrafts[planId] || "").trim();
  if (!body) return;
  const username = currentUser.user_metadata && currentUser.user_metadata.username ? currentUser.user_metadata.username : currentUser.email;
  try {
    const row = await addPlanComment(currentUser.id, username, planId, body);
    (planComments[planId] = planComments[planId] || []).push(row);
    commentDrafts[planId] = "";
    render();
  } catch (e) {
    communityEngagementError = e.message || "Couldn't post your comment.";
    render();
  }
}

async function removeComment(planId, commentId) {
  try {
    await deletePlanComment(commentId);
    planComments[planId] = (planComments[planId] || []).filter((c) => c.id !== commentId);
    render();
  } catch (e) {
    communityEngagementError = e.message || "Couldn't delete the comment.";
    render();
  }
}

function resetSuggestions() {
  suggestedPlaces = null;
  suggestionsLoading = false;
  suggestionsError = null;
  seenSuggestions = new Set();
}

function currentSuggestions() {
  return suggestedPlaces || (selectedHotel && selectedHotel.nearby) || [];
}

// Asks the AI for fresh places to visit around the hotel, skipping ones
// already shown or already in the plan. Part of the plan-building tab.
async function refreshSuggestions() {
  if (!getGeminiKey()) {
    openApiKeyModal(refreshSuggestions);
    return;
  }
  currentSuggestions().forEach((n) => seenSuggestions.add(n.trim().toLowerCase()));
  planCheckDays.flat().forEach((n) => seenSuggestions.add(n.trim().toLowerCase()));
  suggestionsLoading = true;
  suggestionsError = null;
  render();
  try {
    const theme = THEME_META[selectedTheme];
    const exclude = [...seenSuggestions].join("; ");
    const prompt = `Suggest 6 places for a traveler to visit near ${selectedHotel.name} in ${selectedHotel.city}${selectedHotel.country ? ", " + selectedHotel.country : ""}, for a ${theme.label}-themed trip. Mix well-known landmarks with food, culture or activities, all within roughly 30 minutes of the hotel. Use short, commonly recognized names (no descriptions). Do NOT include any of these: ${exclude || "(none)"}.\nRespond with ONLY a JSON array of 6 strings.`;
    const text = await callGemini(prompt, { json: true });
    const parsed = JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g, ""));
    const list = (Array.isArray(parsed) ? parsed : parsed && parsed.places) || [];
    const clean = list.map((x) => String(x).trim()).filter((x) => x && !seenSuggestions.has(x.toLowerCase())).slice(0, 6);
    if (!clean.length) throw new Error("No new ideas came back. Try again.");
    suggestedPlaces = clean;
  } catch (e) {
    suggestionsError = e.message || "Couldn't get new ideas.";
  }
  suggestionsLoading = false;
  render();
}

function addPlanCheckStop(dayIndex, stop) {
  const trimmed = stop.trim();
  if (!trimmed) return;
  planCheckDays[dayIndex].push(trimmed);
  render();
}

function removePlanCheckStop(dayIndex, stopIndex) {
  planCheckDays[dayIndex].splice(stopIndex, 1);
  planCheckResult = null;
  render();
}

// Moving a stop changes which feedback belongs to which stop, so the old
// result is cleared and the customer re-checks.
function movePlanCheckStop(dayIndex, stopIndex, delta) {
  const stops = planCheckDays[dayIndex];
  const target = stopIndex + delta;
  if (target < 0 || target >= stops.length) return;
  [stops[stopIndex], stops[target]] = [stops[target], stops[stopIndex]];
  planCheckResult = null;
  render();
}

// Applies the AI's suggested order only if it's an exact reshuffle of the
// stops already in the day (so a hallucinated name can't add or drop one).
function applySuggestedOrder(dayIndex) {
  const dr = planCheckResult && planCheckResult.days && planCheckResult.days[dayIndex];
  const suggested = dr && dr.betterOrder;
  const current = planCheckDays[dayIndex];
  if (!Array.isArray(suggested) || suggested.length !== current.length) return;
  const pool = [...current];
  const next = [];
  for (const name of suggested) {
    const idx = pool.findIndex((c) => c.trim().toLowerCase() === String(name).trim().toLowerCase());
    if (idx === -1) return;
    next.push(pool.splice(idx, 1)[0]);
  }
  planCheckDays[dayIndex] = next;
  planCheckResult = null;
  render();
}

function addPlanCheckDay() {
  planCheckDays.push([]);
  render();
}

function removePlanCheckDay(dayIndex) {
  if (planCheckDays.length <= 1) return;
  planCheckDays.splice(dayIndex, 1);
  planCheckResult = null;
  render();
}

async function checkMyPlan() {
  if (!getGeminiKey()) {
    openApiKeyModal(checkMyPlan);
    return;
  }
  planCheckLoading = true;
  planCheckError = null;
  render();
  try {
    planCheckResult = await evaluateCustomItinerary(selectedHotel, selectedTheme, planCheckDays);
  } catch (e) {
    planCheckError = e.message || "Something went wrong checking the plan.";
  }
  planCheckLoading = false;
  render();
}

// ---------- rendering ----------

const root = document.getElementById("app");

function escapeHtml(s) {
  const div = document.createElement("div");
  div.textContent = s;
  return div.innerHTML;
}

function timeAgo(ms) {
  const hours = (Date.now() - ms) / 3600000;
  if (hours < 1) return "just now";
  if (hours < 24) return Math.round(hours) + "h ago";
  return Math.round(hours / 24) + "d ago";
}

function renderAccountControl() {
  if (!isSupabaseConfigured()) return "";
  if (currentUser) {
    const username = currentUser.user_metadata && currentUser.user_metadata.username ? currentUser.user_metadata.username : currentUser.email;
    return `<span class="account-pill">👤 ${escapeHtml(username)} <button class="account-signout" id="sign-out-btn">Sign out</button></span>`;
  }
  return `<button class="journal-badge" id="sign-in-btn">Sign in</button>`;
}

// Where "Plan" should return to: the furthest point of the current trip.
function planStep() {
  if (selectedHotel && selectedTheme) return "answer";
  if (selectedTheme) return "hotel";
  if (selectedCity) return "theme";
  return "city";
}

// Line icons (24px grid, stroke follows the text color) for the menus.
const ICON_PATHS = {
  plan: '<circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/>',
  community: '<circle cx="12" cy="12" r="10"/><path d="M2 12h20"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>',
  journal: '<path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/>',
  hotel: '<path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path d="M10 6h4"/><path d="M10 10h4"/><path d="M10 14h4"/><path d="M10 18h4"/>',
  trophy: '<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6"/><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22"/><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22"/><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z"/>',
  crown: '<path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"/><path d="M5 21h14"/>',
  clock: '<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>',
  calendar: '<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/>',
  feed: '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
  camera: '<path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3z"/><circle cx="12" cy="13" r="3.5"/>',
};

function icon(name) {
  return `<svg class="icon" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICON_PATHS[name]}</svg>`;
}

function renderBottomNav() {
  const active = step === "community" ? "community" : step === "feed" ? "feed" : step === "journal" ? "journal" : "plan";
  const item = (key, icon, label) =>
    `<button class="nav-item ${active === key ? "nav-active" : ""}" data-nav="${key}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`;
  return `<nav class="bottom-nav">
    ${item("plan", icon("plan"), "Plan")}
    ${isSupabaseConfigured() ? item("community", icon("community"), "Community") : ""}
    ${isSupabaseConfigured() ? item("feed", icon("feed"), "Feed") : ""}
    ${item("journal", icon("journal"), "Journal")}
  </nav>`;
}

function render() {
  root.classList.toggle("wide", step === "answer" && answerTab === "plan");
  root.innerHTML = `
    <header class="topbar">
      <div class="topbar-row">
        <button class="brand brand-btn" data-plan-new title="Start a new trip">${LOGO_SVG} Travelify</button>
        <div class="header-right">${renderAccountControl()}</div>
      </div>
    </header>
    <main>${renderStep()}</main>
    ${renderBottomNav()}
  `;
  bindEvents();
  saveSession();
}

function renderStep() {
  if (step === "city") return renderCityStep();
  if (step === "theme") return renderThemeStep();
  if (step === "hotel") return renderHotelStep();
  if (step === "answer") return renderAnswerStep();
  if (step === "journal") return renderJournal();
  if (step === "community") return renderCommunityStep();
  if (step === "feed") return renderFeedStep();
  return "";
}

function followButton(userId, username) {
  if (!isSupabaseConfigured() || (currentUser && currentUser.id === userId)) return "";
  const on = followingIds.has(userId);
  return `<button type="button" class="follow-btn ${on ? "follow-on" : ""}" data-follow="${userId}" data-follow-name="${escapeHtml(username)}">${on ? "Following" : "Follow"}</button>`;
}

function planCardHtml(p, rank) {
      const theme = THEME_META[p.theme_key];
      const v = planVotes[p.id] || { up: 0, down: 0, mine: 0 };
      const comments = planComments[p.id] || [];
      const open = expandedComments.has(p.id);
      const commentList = comments
        .map(
          (c) => `
          <div class="comment-row">
            <div><strong>${escapeHtml(c.username)}</strong> <span class="rank-sub">· ${timeAgo(new Date(c.created_at).getTime())}</span>
              ${currentUser && c.user_id === currentUser.id ? `<button type="button" class="icon-btn comment-delete" data-delete-comment="${p.id}|${c.id}">Delete</button>` : ""}
            </div>
            <div class="comment-body">${escapeHtml(c.body)}</div>
          </div>`
        )
        .join("");
      const commentBox = open
        ? `
        <div class="comments-box">
          ${commentList || `<p class="rank-sub">No comments yet.</p>`}
          <form class="custom-add" data-comment-form="${p.id}">
            <input type="text" maxlength="1000" placeholder="${currentUser ? "Add a comment…" : "Sign in to comment"}" value="${escapeHtml(commentDrafts[p.id] || "")}" data-comment-input="${p.id}" />
            <button type="submit" class="pill-btn ghost">Post</button>
          </form>
        </div>`
        : "";
  return `
      <li class="plan-card">
        <div class="plan-card-head">${rank ? `<span class="rank-chip rank-${rank <= 3 ? rank : "n"}">${rank}</span>` : ""}<div class="rank-name">${theme ? theme.emoji : ""} ${escapeHtml(p.hotel_name)}</div></div>
        <div class="rank-sub">${escapeHtml(p.city)} · by ${escapeHtml(p.username)} ${followButton(p.user_id, p.username)} · ${p.score}% ${theme ? theme.label : ""} fit</div>
        <p class="rank-sub plan-card-text">${escapeHtml(p.plan_text)}</p>
        <div class="engage-row">
          <button type="button" class="engage-btn ${v.mine === 1 ? "engage-active-up" : ""}" data-vote="${p.id}|1">👍 ${v.up}</button>
          <button type="button" class="engage-btn ${v.mine === -1 ? "engage-active-down" : ""}" data-vote="${p.id}|-1">👎 ${v.down}</button>
          <button type="button" class="engage-btn" data-toggle-comments="${p.id}">💬 ${comments.length}</button>
        </div>
        ${commentBox}
      </li>`;
}

function renderCommunityTabs() {
  const t = (key, iconName, label) =>
    `<button class="tab-btn ${communityView === key ? "tab-active" : ""}" data-community-view="${key}">${icon(iconName)}${label}</button>`;
  return `<div class="tabs">${t("latest", "clock", "Latest")}${t("plans", "trophy", "Top plans")}${t("creators", "crown", "Top creators")}</div>`;
}

function renderRanking() {
  if (rankingLoading) return `<div class="empty">Loading rankings…</div>`;
  if (rankingError) return `<p class="rank-sub plan-error">${escapeHtml(rankingError)}</p>`;

  if (communityView === "plans") {
    const intro = `<p class="rank-sub">Most liked plans from the last ${RECENT_DAYS} days.</p>`;
    if (!ranking.plans.length) return intro + `<div class="empty">No liked plans yet this month. Share one and get it liked!</div>`;
    return intro + `<ul class="rank-list">${ranking.plans.map((p, i) => planCardHtml(p, i + 1)).join("")}</ul>`;
  }

  const intro = `<p class="rank-sub">Creators ranked by total likes on their public plans.</p>`;
  if (!ranking.creators.length) return intro + `<div class="empty">No likes yet. Be the first creator on the board!</div>`;
  const mine = currentUser && ranking.myRank ? `<div class="my-rank">Your rank: <strong>#${ranking.myRank}</strong> · ${ranking.myLikes} like${ranking.myLikes === 1 ? "" : "s"}</div>` : "";
  const rows = ranking.creators
    .map((u, i) => {
      const me = currentUser && u.user_id === currentUser.id;
      return `
      <li class="creator-row ${me ? "creator-me" : ""}">
        <span class="rank-chip rank-${i < 3 ? i + 1 : "n"}">${i + 1}</span>
        <div class="rank-info">
          <div class="rank-name">${escapeHtml(u.username)}${me ? ` <span class="you-tag">You</span>` : ""}</div>
          <div class="rank-sub">${u.plans} plan${u.plans === 1 ? "" : "s"}${u.best ? ` · top: ${escapeHtml(u.best.hotel_name)}` : ""}</div>
        </div>
        ${followButton(u.user_id, u.username)}
        <span class="likes-pill">👍 ${u.likes}</span>
      </li>`;
    })
    .join("");
  return intro + mine + `<ul class="rank-list">${rows}</ul>`;
}

function renderCommunityStep() {
  const header = `
    <h2 class="step-heading">Community</h2>
    ${renderCommunityTabs()}
  `;

  if (communityView !== "latest") return header + renderRanking();

  if (communityLoading) return header + `<div class="empty">Loading…</div>`;
  if (communityError) return header + `<div class="empty">${escapeHtml(communityError)}</div>`;
  if (communityPlans.length === 0) return header + `<div class="empty">No shared plans yet — be the first!</div>`;

  const cards = communityPlans.map((p) => planCardHtml(p)).join("");
  const engageNote = communityEngagementError ? `<p class="rank-sub plan-error">${escapeHtml(communityEngagementError)}</p>` : "";
  return header + engageNote + `<ul class="rank-list">${cards}</ul>`;
}

function renderFeedStep() {
  const header = `<h2 class="step-heading">Feed</h2><p class="rank-sub">Trips from travelers you follow.</p>`;
  if (!currentUser) {
    return header + `<div class="empty">Sign in to follow travelers and see their trips here.<br /><br /><button class="pill-btn" data-feed-signin>Sign in</button></div>`;
  }
  const errorNote = followError ? `<p class="rank-sub plan-error">${escapeHtml(followError)}</p>` : "";

  const followingList = followingIds.size
    ? `<details class="share-details">
        <summary>Following (${followingIds.size})</summary>
        <ul class="rank-list">${[...followingIds]
          .map(
            (id) => `<li class="creator-row"><div class="rank-info"><div class="rank-name">${escapeHtml(followNames[id] || "Traveler")}</div></div>${followButton(id, followNames[id] || "Traveler")}</li>`
          )
          .join("")}</ul>
      </details>`
    : "";

  let body;
  if (feedLoading) {
    body = `<div class="empty">Loading…</div>`;
  } else if (feedError) {
    body = `<p class="rank-sub plan-error">${escapeHtml(feedError)}</p>`;
  } else if (!followingIds.size) {
    body = `<div class="empty">You're not following anyone yet. Follow travelers below, or tap Follow on a plan in Community.</div>`;
  } else if (!feedEntries.length) {
    body = `<div class="empty">Nothing here yet. The travelers you follow haven't made their journal public or added any trips.</div>`;
  } else {
    body = `<ul class="rank-list">${feedEntries
      .map((j, idx) => {
        const theme = THEME_META[j.themeKey] || { emoji: "🧳", label: "" };
        const color = j.score >= 75 ? "#2e7d4f" : j.score >= 50 ? "#b8860b" : "#c0392b";
        return `
        <li><button class="rank-row" data-open-feed="${idx}">
          <div class="rank-info">
            <div class="rank-sub"><strong>${escapeHtml(followNames[j.userId] || "Traveler")}</strong> · ${timeAgo(j.timestamp)}</div>
            <div class="rank-name">${theme.emoji} ${escapeHtml(j.hotelName)}</div>
            <div class="rank-sub">${escapeHtml(j.city)}${theme.label ? " · " + theme.label : ""}</div>
          </div>
          <span class="badge" style="background:${color}">${j.score}%</span>
        </button></li>`;
      })
      .join("")}</ul>`;
  }

  // People to follow: authors of recent community plans I don't follow yet.
  const seen = new Set();
  const suggestions = communityPlans
    .filter((p) => p.user_id !== currentUser.id && !followingIds.has(p.user_id) && !seen.has(p.user_id) && seen.add(p.user_id))
    .slice(0, 8);
  const suggestionBlock = suggestions.length
    ? `<div class="detail-label feed-suggest-label">Travelers to follow</div>
       <ul class="rank-list">${suggestions
         .map((p) => `<li class="creator-row"><div class="rank-info"><div class="rank-name">${escapeHtml(p.username)}</div><div class="rank-sub">Shared a plan for ${escapeHtml(p.city)}</div></div>${followButton(p.user_id, p.username)}</li>`)
         .join("")}</ul>`
    : "";

  return header + errorNote + followingList + body + suggestionBlock;
}

function renderStepper(current) {
  const items = ["City", "Vibe", "Hotel"];
  return `<div class="stepper">${items
    .map((label, i) => `<span class="stepper-item ${i + 1 === current ? "stepper-active" : i + 1 < current ? "stepper-done" : ""}"><span class="stepper-num">${i + 1 < current ? "✓" : i + 1}</span>${label}</span>`)
    .join('<span class="stepper-line"></span>')}</div>`;
}

function popularCities(limit) {
  const counts = {};
  MOCK_HOTELS.forEach((h) => (counts[h.city] = (counts[h.city] || 0) + 1));
  return Object.keys(counts)
    .sort((a, b) => counts[b] - counts[a] || a.localeCompare(b))
    .slice(0, limit);
}

function renderCityStep() {
  const rawQuery = cityQuery.trim();
  const q = rawQuery.toLowerCase();
  const allCities = uniqueCities();
  const cities = allCities.filter((c) => (q ? c.toLowerCase().includes(q) : true));
  const cityButton = (c) => `<button class="rank-row city-row" data-pick-city="${escapeHtml(c)}">${escapeHtml(c)}</button>`;

  const exactMatch = allCities.some((c) => c.toLowerCase() === q);
  const useTypedCity =
    rawQuery && !exactMatch
      ? `<button class="pill-btn ghost use-typed-city" data-pick-city="${escapeHtml(rawQuery)}">Use "${escapeHtml(rawQuery)}" as my city</button>`
      : "";

  let body;
  if (rawQuery) {
    body = `<div class="rank-list">${cities.map(cityButton).join("")}</div>${useTypedCity}`;
  } else {
    const popular = popularCities(8)
      .map((c) => `<button class="chip" data-pick-city="${escapeHtml(c)}">${escapeHtml(c)}</button>`)
      .join("");
    body = `
      <div class="detail-label">Popular</div>
      <div class="chip-row popular-row">${popular}</div>
      <button class="pill-btn ghost" data-show-all-cities>${showAllCities ? "Hide full list" : `Browse all ${allCities.length} cities`}</button>
      ${showAllCities ? `<div class="rank-list all-cities">${allCities.map(cityButton).join("")}</div>` : ""}`;
  }

  return `
    ${renderStepper(1)}
    <h2 class="step-heading">Where are you traveling?</h2>
    <div class="search-wrap">
      <input id="city-input" type="text" placeholder="Type a city, e.g. Paris" value="${escapeHtml(cityQuery)}" />
    </div>
    ${body}
  `;
}

function renderThemeStep() {
  const cards = THEME_KEYS.map((key) => {
    const t = THEME_META[key];
    return `
      <button class="theme-card" data-pick-theme="${key}">
        <div class="theme-emoji">${t.emoji}</div>
        <div class="theme-label">${t.label}</div>
        <div class="rank-sub">${t.blurb}</div>
      </button>`;
  }).join("");

  return `
    ${renderStepper(2)}
    <button class="icon-btn back-btn" data-step="city">← Change city</button>
    <h2 class="step-heading">What's the vibe for this trip?</h2>
    <p class="rank-sub">Traveling to ${escapeHtml(selectedCity)}</p>
    <div class="theme-grid">${cards}</div>
  `;
}

function renderHotelStep() {
  const theme = THEME_META[selectedTheme];
  const hotels = hotelsInCity(selectedCity)
    .map((h) => ({ hotel: h, fit: evaluateFit(h, selectedTheme) }))
    .sort((a, b) => b.fit.score - a.fit.score);

  const rows = hotels
    .map(
      ({ hotel: h, fit }) => `
      <button class="rank-row hotel-row" data-pick-hotel="${h.id}">
        <div class="rank-info">
          <div class="rank-name">${escapeHtml(h.name)}</div>
          <div class="rank-sub">${escapeHtml(TIER_META[h.tier].label)}${h.tags && h.tags.length ? " · " + h.tags.slice(0, 3).join(", ") : ""}</div>
        </div>
        <span class="badge" style="background:${fit.color}">${fit.score}%</span>
      </button>`
    )
    .join("");

  const customForm = showCustomHotelForm
    ? `
    <form id="custom-hotel-form" class="custom-add">
      <input id="custom-hotel-name" type="text" placeholder="Hotel name" required />
      <button type="submit" class="pill-btn">Use this hotel</button>
    </form>`
    : `<button class="pill-btn ghost" id="show-custom-hotel">Can't find it? Enter it manually</button>`;

  return `
    ${renderStepper(3)}
    <button class="icon-btn back-btn" data-step="theme">← Change theme</button>
    <h2 class="step-heading">Choose your hotel in ${escapeHtml(selectedCity)}</h2>
    <p class="rank-sub">${theme.emoji} ${theme.label} trip · scores show fit for this vibe</p>
    <div class="rank-list">${rows || `<div class="empty">No hotels on file for ${escapeHtml(selectedCity)} yet.</div>`}</div>
    <div class="custom-add-wrap">${customForm}</div>
  `;
}

function renderAnswerStep() {
  const hotel = selectedHotel;
  const theme = THEME_META[selectedTheme];
  const fit = evaluateFit(hotel, selectedTheme);

  const reasonsList = fit.reasons.map((r) => `<li>${escapeHtml(r)}</li>`).join("");

  const gt = gettingThereUrls(hotel);
  const mapsLink = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(hotel.address || [hotel.name, hotel.city].join(" "))}`;
  const infoCard = `
    <div class="info-card">
      ${hotel.address ? `<div class="info-row"><span>📍</span><a href="${mapsLink}" target="_blank" rel="noopener">${escapeHtml(hotel.address)}</a></div>` : ""}
      ${hotel.nearby && hotel.nearby.length ? `<div class="info-row"><span>🗺️</span><div>Near ${hotel.nearby.map(escapeHtml).join(" · ")}</div></div>` : ""}
      <div class="info-row"><span>✈️</span><div>From the airport: <a href="${gt.transit}" target="_blank" rel="noopener">transit</a> · <a href="${gt.driving}" target="_blank" rel="noopener">drive</a></div></div>
    </div>`;

  const links = hotel.website
    ? `
    <div class="detail-links">
      <a class="pill-btn" href="${hotel.website}" target="_blank" rel="noopener">📅 Book on Official Site</a>
    </div>`
    : `
    <div class="detail-links">
      <a class="pill-btn ghost" href="${hotelSearchFallbackUrl(hotel)}" target="_blank" rel="noopener">🔍 Search for this hotel</a>
    </div>
    <p class="rank-sub getting-there-note">No official site on file for this hotel — this opens a general search instead.</p>`;

  return `
    <button class="icon-btn back-btn" data-step="hotel">← Change hotel</button>
    <div class="answer-header">
      <span class="badge answer-badge" style="background:${fit.color}">${fit.score}%</span>
      <div>
        <div class="answer-verdict">${fit.verdict}</div>
        <div class="rank-sub">${theme.emoji} ${theme.label} trip at ${escapeHtml(hotel.name)}</div>
      </div>
    </div>

    <div class="tabs">
      <button class="tab-btn ${answerTab === "hotel" ? "tab-active" : ""}" data-answer-tab="hotel">${icon("hotel")}Hotel</button>
      <button class="tab-btn ${answerTab === "plan" ? "tab-active" : ""}" data-answer-tab="plan">${icon("calendar")}Plan my days</button>
    </div>

    ${
      answerTab === "plan"
        ? renderPlanCheckSection()
        : `
    <ul class="reasons-list">${reasonsList}</ul>
    ${infoCard}
    <div class="action-stack">
      <button class="pill-btn cta-plan" data-answer-tab="plan">🗓️ Plan my days here →</button>
      ${links}
    </div>`
    }

    <div class="detail-actions">
      <button class="icon-btn" data-step="theme">Try a different vibe</button>
    </div>
  `;
}

function quickAddChips(dayIndex, stops) {
  const used = new Set(stops.map((x) => x.trim().toLowerCase()));
  const chips = currentSuggestions()
    .map((name, ni) => ({ name, ni }))
    .filter(({ name }) => !used.has(name.trim().toLowerCase()))
    .map(({ name, ni }) => `<button type="button" class="chip quick-chip" data-quick-add="${dayIndex}|${ni}">+ ${escapeHtml(name)}</button>`)
    .join("");
  const refresh = `<button type="button" class="chip quick-chip refresh-chip" data-refresh-suggestions ${suggestionsLoading ? "disabled" : ""}>${suggestionsLoading ? "Finding…" : "🔄 More ideas"}</button>`;
  return `<div class="quick-add"><div class="rank-sub">Tap to add a place near you:</div><div class="chip-row">${chips}${refresh}</div>${suggestionsError ? `<p class="rank-sub plan-error">${escapeHtml(suggestionsError)}</p>` : ""}</div>`;
}

function renderPlanCheckSection() {
  const structured = planCheckResult && !planCheckResult.raw ? planCheckResult : null;

  const verdictClass = (v) => (v === "good" ? "feedback-good" : "feedback-review");
  const keywordChips = (kws) =>
    kws && kws.length ? `<div class="kw-row">${kws.map((k) => `<span class="kw-chip">${escapeHtml(String(k))}</span>`).join("")}</div>` : "";

  const stopFeedback = (st) =>
    st
      ? `<div class="feedback-card ${verdictClass(st.verdict)}">
          <div class="feedback-text">${st.verdict === "good" ? "✅" : "⚠️"} ${escapeHtml(st.feedback || "")}</div>
          ${keywordChips(st.keywords)}
        </div>`
      : "";

  const MODE_ICON = { walk: "🚶", subway: "🚇", bus: "🚌", train: "🚆", taxi: "🚕", car: "🚗" };
  const legMeta = (leg) => {
    const parts = [];
    const mode = String(leg.mode || "").toLowerCase();
    if (mode) parts.push(`${MODE_ICON[mode] || "➡️"} ${mode.charAt(0).toUpperCase() + mode.slice(1)}`);
    if (leg.minutes) parts.push(`~${escapeHtml(String(leg.minutes))} min`);
    if (leg.cost) parts.push(escapeHtml(String(leg.cost).startsWith("~") || String(leg.cost).toLowerCase() === "free" ? String(leg.cost) : "~" + String(leg.cost)));
    return parts.length ? `<div class="leg-meta">${parts.join(" · ")}</div>` : "";
  };
  const legFeedback = (leg) =>
    leg ? `<div class="feedback-card feedback-leg ${verdictClass(leg.verdict)}">${legMeta(leg)}<div class="feedback-text">${leg.verdict === "good" ? "✅" : "⚠️"} ${escapeHtml(leg.feedback || "")}</div></div>` : "";

  const photoStrip = (stopName, i, si) => {
    const photos = photoCache[stopPhotoKey(stopName)] || [];
    const thumbs = photos
      .map((p) => `<button type="button" class="photo-thumb" data-open-photo="${p.id}"><img src="${p.thumbUrl}" alt="Photo from ${escapeHtml(stopName)}" /></button>`)
      .join("");
    const addBtn =
      photos.length >= MAX_PHOTOS_PER_STOP
        ? ""
        : `<label class="photo-add">${icon("camera")}<span>${photos.length ? "Add" : "Add photos"}</span><input type="file" accept="image/*" multiple hidden data-photo-input="${i}|${si}" /></label>`;
    return `<div class="photo-strip">${thumbs}${addBtn}</div>`;
  };

  const dayBlocks = planCheckDays
    .map((stops, i) => {
      const dr = structured && structured.days[i];
      const removeBtn = planCheckDays.length > 1 ? `<button type="button" class="icon-btn" data-remove-day="${i}">Remove day</button>` : "";

      const rows = stops
        .map((s, si) => {
          const stopRow = `
          <div class="plan-row">
            <div class="plan-col"><span class="stop-chip">
              <span class="stop-move">
                <button type="button" class="stop-move-btn" data-move-stop="${i}|${si}|-1" ${si === 0 ? "disabled" : ""} title="Move earlier">▲</button>
                <button type="button" class="stop-move-btn" data-move-stop="${i}|${si}|1" ${si === stops.length - 1 ? "disabled" : ""} title="Move later">▼</button>
              </span>
              ${escapeHtml(s)} <button type="button" class="stop-chip-remove" data-remove-stop="${i}-${si}">✕</button></span>
              ${photoStrip(s, i, si)}</div>
            <div class="feedback-col">${planCheckLoading ? "" : stopFeedback(dr && dr.stops && dr.stops[si])}</div>
          </div>`;
          const hasNext = si < stops.length - 1;
          const legRow = hasNext
            ? `
          <div class="plan-row plan-leg-row">
            <div class="plan-col plan-leg">↓ ${escapeHtml(s)} → ${escapeHtml(stops[si + 1])}</div>
            <div class="feedback-col">${planCheckLoading ? "" : legFeedback(dr && dr.legs && dr.legs[si])}</div>
          </div>`
            : "";
          return stopRow + legRow;
        })
        .join("");

      const dayAnyReview = dr && [...(dr.stops || []), ...(dr.legs || [])].some((x) => x && x.verdict !== "good");
      const dayStats =
        dr && !planCheckLoading
          ? `<div class="feedback-card feedback-day ${dayAnyReview ? "feedback-review" : "feedback-good"}"><div class="feedback-stats">Day ${i + 1}: ~${escapeHtml(String(dr.walkingKm))} km walking · ~${escapeHtml(String(dr.kcal))} kcal${dr.travelMinutes ? ` · ~${escapeHtml(String(dr.travelMinutes))} min getting around` : ""}${dr.travelCost ? ` · ${escapeHtml(String(dr.travelCost).startsWith("~") || String(dr.travelCost).toLowerCase() === "free" ? String(dr.travelCost) : "~" + String(dr.travelCost))} transport` : ""}</div></div>`
          : "";

      let orderRow = "";
      if (dr && !planCheckLoading && stops.length > 1) {
        const better = Array.isArray(dr.betterOrder) && dr.betterOrder.length === stops.length ? dr.betterOrder : null;
        orderRow = better
          ? `<div class="plan-row">
              <div class="plan-col plan-leg">🔀 Order of stops</div>
              <div class="feedback-col"><div class="feedback-card feedback-review">
                <div class="feedback-text"><strong>Try this order:</strong> ${better.map((n) => escapeHtml(String(n))).join(" → ")}</div>
                ${dr.orderNote ? `<div class="feedback-text">${escapeHtml(dr.orderNote)}</div>` : ""}
                <button type="button" class="pill-btn apply-order-btn" data-apply-order="${i}">Apply this order</button>
              </div></div>
            </div>`
          : `<div class="plan-row">
              <div class="plan-col plan-leg">🔀 Order of stops</div>
              <div class="feedback-col"><div class="feedback-card feedback-leg feedback-good"><div class="feedback-text">✅ ${escapeHtml(dr.orderNote || "This order works well.")}</div></div></div>
            </div>`;
      }

      return `
      <div class="plan-check-day">
        <div class="plan-day-label">Day ${i + 1} ${removeBtn}</div>
        ${stops.length ? rows : `<p class="rank-sub">No stops added yet.</p>`}
        ${orderRow}
        <div class="plan-row">
          <div class="plan-col">
            ${quickAddChips(i, stops)}
            <form class="custom-add" data-add-stop-form="${i}">
              <input type="text" placeholder="Add a place (e.g. Eiffel Tower)" />
              <button type="submit" class="pill-btn ghost">Add</button>
            </form>
          </div>
          <div class="feedback-col">${dayStats}</div>
        </div>
      </div>`;
    })
    .join("");

  let resultBlock = "";
  if (planCheckError) {
    resultBlock = `
      <p class="rank-sub plan-error">${escapeHtml(planCheckError)}</p>
      <button class="icon-btn change-key-btn">Change API key</button>`;
  } else if (planCheckResult && planCheckResult.raw) {
    resultBlock = `<p class="rank-sub ai-plan-text">${escapeHtml(planCheckResult.raw)}</p>`;
  } else if (structured && !planCheckLoading) {
    resultBlock = `
      <div class="plan-summary">
        ${keywordChips(structured.keywords)}
        ${structured.summary ? `<div>${escapeHtml(structured.summary)}</div>` : ""}
        ${structured.totalKcal ? `<div class="plan-summary-total">Total: ~${escapeHtml(String(structured.totalKcal))} kcal over ${planCheckDays.length} day${planCheckDays.length > 1 ? "s" : ""} (rough estimate)</div>` : ""}
        ${structured.totalTravelCost ? `<div class="plan-summary-total">Getting around: ~${escapeHtml(String(structured.totalTravelCost).replace(/^~/, ""))} total per person (rough estimate)</div>` : ""}
      </div>`;
  }

  const hasAnyStops = planCheckDays.some((d) => d.length > 0);

  const shareBlock = isSupabaseConfigured()
    ? sharePlanSuccess
      ? `<p class="rank-sub">🎉 Shared with the community! Check the 🌍 Community tab.</p>`
      : `
      <details class="share-details" data-share-details ${shareOpen ? "open" : ""}>
        <summary>🌍 Share this plan with the community</summary>
        <textarea id="plan-check-notes" class="plan-textarea" rows="3" placeholder="Add a note for other travelers (optional)">${escapeHtml(planCheckNotes)}</textarea>
        ${sharePlanError ? `<p class="rank-sub plan-error">${escapeHtml(sharePlanError)}</p>` : ""}
        <button class="pill-btn" id="share-plan-btn" ${sharePlanLoading || !hasAnyStops ? "disabled" : ""}>${sharePlanLoading ? "Sharing…" : "Share"}</button>
        ${!currentUser ? `<p class="rank-sub">Sign in to share your plan publicly.</p>` : ""}
      </details>`
    : "";

  return `
  <div class="detail-section plan-section">
    <div class="detail-label">📍 Check My Plan</div>
    <p class="rank-sub">Add the places you want to visit each day, then tap Check My Plan. You'll get feedback on every stop and the order, plus walking and calories. After your trip, add photos to any stop — they stay on this device.</p>
    ${photoNotice ? `<p class="rank-sub plan-error">${escapeHtml(photoNotice)}</p>` : ""}
    <div class="detail-label transport-label">Getting around</div>
    <div class="chip-row transport-row">
      ${[["auto", "✨ Best for the city"], ["transit", "🚇 Subway / transit"], ["taxi", "🚕 Taxi / rideshare"]]
        .map(([key, label]) => `<button type="button" class="chip ${planTransport === key ? "chip-active" : ""}" data-transport="${key}">${label}</button>`)
        .join("")}
    </div>
    ${dayBlocks}
    <button type="button" class="pill-btn ghost" id="add-day-btn">+ Add Day</button>
    <button class="pill-btn" id="check-plan-btn" ${planCheckLoading || !hasAnyStops ? "disabled" : ""}>${planCheckLoading ? "Checking… (this can take a little while)" : "🔍 Check My Plan"}</button>
    ${resultBlock}
    ${shareBlock}
  </div>`;
}

// ---------- auth modal ----------

function openAuthModal(initialMode) {
  let mode = initialMode || "signin";

  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";

  function paint() {
    overlay.innerHTML = `
      <div class="share-modal">
        <button class="icon-btn share-modal-close" id="auth-modal-close">✕ Close</button>
        <h3 class="step-heading">${mode === "signin" ? "Sign In" : "Create Account"}</h3>
        <form id="auth-form" class="custom-add" style="flex-direction:column; gap:10px;">
          ${mode === "signup" ? `<input id="auth-username" type="text" placeholder="Username" required autocomplete="username" />` : ""}
          <input id="auth-email" type="email" placeholder="Email" required autocomplete="email" />
          <input id="auth-password" type="password" placeholder="Password" required autocomplete="${mode === "signin" ? "current-password" : "new-password"}" minlength="6" />
          <button type="submit" class="pill-btn" ${authLoading ? "disabled" : ""}>${authLoading ? "Please wait…" : mode === "signin" ? "Sign In" : "Create Account"}</button>
        </form>
        ${authError ? `<p class="rank-sub plan-error">${escapeHtml(authError)}</p>` : ""}
        <p class="rank-sub share-modal-note">
          ${mode === "signin" ? "New here?" : "Already have an account?"}
          <a href="#" id="auth-switch-mode">${mode === "signin" ? "Create an account" : "Sign in"}</a>
        </p>
      </div>
    `;

    document.getElementById("auth-modal-close").addEventListener("click", () => overlay.remove());
    document.getElementById("auth-switch-mode").addEventListener("click", (e) => {
      e.preventDefault();
      mode = mode === "signin" ? "signup" : "signin";
      authError = null;
      paint();
    });
    document.getElementById("auth-form").addEventListener("submit", async (e) => {
      e.preventDefault();
      const email = document.getElementById("auth-email").value.trim();
      const password = document.getElementById("auth-password").value;
      const username = mode === "signup" ? document.getElementById("auth-username").value.trim() : null;
      authLoading = true;
      authError = null;
      paint();
      try {
        if (mode === "signup") {
          await signUp(email, password, username);
        } else {
          await signIn(email, password);
        }
        authLoading = false;
        overlay.remove();
      } catch (err) {
        authLoading = false;
        authError = err.message || "Something went wrong.";
        paint();
      }
    });
  }

  paint();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) overlay.remove();
  });
  document.body.appendChild(overlay);
}

// ---------- API key modal ----------
// Shared by every AI feature (Plan the Trip, Check My Plan) so the key
// prompt always appears the same way regardless of which one triggered
// it, instead of being embedded inline in just one feature's section.

function openApiKeyModal(onSaved) {
  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";
  overlay.innerHTML = `
    <div class="share-modal">
      <button class="icon-btn share-modal-close" id="key-modal-close">✕ Close</button>
      <h3 class="step-heading">AI API key</h3>
      <p class="rank-sub">Stored only in this browser's localStorage — never written to a file, never committed to git. Get a key at <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener">aistudio.google.com/apikey</a>.</p>
      <form id="api-key-form" class="custom-add">
        <input id="api-key-input" type="password" placeholder="Paste your AI API key" required autocomplete="off" />
        <button type="submit" class="pill-btn">Save</button>
      </form>
    </div>`;
  document.body.appendChild(overlay);

  const close = () => overlay.remove();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.getElementById("key-modal-close").addEventListener("click", close);
  document.getElementById("api-key-form").addEventListener("submit", (e) => {
    e.preventDefault();
    const key = document.getElementById("api-key-input").value.trim();
    if (!key) return;
    setGeminiKey(key);
    close();
    onSaved();
  });
}

// ---------- shareable match card ----------
// Renders the fit result as a downloadable/shareable PNG (canvas, drawn
// client-side — no server, no image-generation API). This is the app's
// main growth lever: the shared image doubles as an ad for Travelify.

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-+|-+$)/g, "") || "hotel";
}

function wrapCenteredText(ctx, text, x, y, maxWidth, lineHeight, maxLines) {
  const words = text.split(" ");
  let line = "";
  const lines = [];
  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + " ";
    if (ctx.measureText(testLine).width > maxWidth && n > 0) {
      lines.push(line.trim());
      line = words[n] + " ";
    } else {
      line = testLine;
    }
  }
  lines.push(line.trim());
  const clipped = maxLines ? lines.slice(0, maxLines) : lines;
  clipped.forEach((l, i) => ctx.fillText(l, x, y + i * lineHeight));
  return clipped.length;
}

function drawShareLogo(ctx, x, y, size) {
  const scale = size / 32;
  ctx.save();
  ctx.translate(x, y);
  ctx.scale(scale, scale);
  ctx.fillStyle = LOGO_GREEN;
  ctx.beginPath();
  ctx.roundRect(0, 0, 32, 32, 9);
  ctx.fill();
  ctx.fillStyle = "#fff";
  ctx.fill(new Path2D(LOGO_PIN_PATH));
  ctx.fillStyle = LOGO_GREEN;
  ctx.beginPath();
  ctx.arc(16, 12.8, 2.7, 0, Math.PI * 2);
  ctx.fill();
  ctx.restore();
}

function buildBadgeCanvas(badge) {
  const W = 1080;
  const H = 1920;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  const font = (weight, size, style) => `${style ? style + " " : ""}${weight} ${size}px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`;

  const bgGrad = ctx.createLinearGradient(0, 0, 0, H);
  bgGrad.addColorStop(0, "#eaf4ec");
  bgGrad.addColorStop(1, "#ffffff");
  ctx.fillStyle = bgGrad;
  ctx.fillRect(0, 0, W, H);

  drawShareLogo(ctx, 90, 115, 64);
  ctx.fillStyle = "#1c1b19";
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.font = font(700, 48);
  ctx.fillText("Travelify", 170, 147);

  ctx.textAlign = "center";
  ctx.textBaseline = "alphabetic";
  ctx.font = font(600, 40);
  ctx.fillStyle = "#7a756c";
  ctx.fillText("🏅 Achievement Unlocked", W / 2, 560);

  ctx.font = font(400, 260);
  ctx.fillText(badge.emoji, W / 2, 820);

  ctx.fillStyle = "#1c1b19";
  ctx.font = font(700, 72);
  wrapCenteredText(ctx, badge.label, W / 2, 940, 880, 84, 2);

  ctx.font = font(400, 40);
  ctx.fillStyle = "#7a756c";
  wrapCenteredText(ctx, badge.description, W / 2, 1060, 760, 54, 3);

  ctx.strokeStyle = "#e7e2da";
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(90, H - 160);
  ctx.lineTo(W - 90, H - 160);
  ctx.stroke();

  ctx.fillStyle = "#7a756c";
  ctx.font = font(500, 34);
  ctx.fillText("Earn your own badges at Travelify", W / 2, H - 90);

  return canvas;
}

function openBadgeShareModal(badge) {
  const canvas = buildBadgeCanvas(badge);
  openCanvasShareModal(canvas, {
    altText: `${badge.label} badge`,
    filename: `travelify-badge-${badge.id}.png`,
    shareText: `I just earned the "${badge.label}" badge on Travelify! ${badge.emoji}`,
  });
}

function openCanvasShareModal(canvas, { altText, filename, shareText }) {
  const dataUrl = canvas.toDataURL("image/png");
  const canShareNative = typeof navigator.share === "function";

  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";
  overlay.innerHTML = `
    <div class="share-modal">
      <button class="icon-btn share-modal-close" id="share-modal-close">✕ Close</button>
      <div class="share-canvas-wrap"><img src="${dataUrl}" alt="${escapeHtml(altText)}" /></div>
      <div class="share-modal-actions">
        <button class="pill-btn" id="share-download-btn">⬇️ Download</button>
        ${canShareNative ? `<button class="pill-btn ghost" id="share-native-btn">📤 Share</button>` : ""}
      </div>
      <p class="rank-sub share-modal-note">Long-press or right-click the image to save it, or use the buttons above — great for Instagram Stories or TikTok.</p>
    </div>
  `;
  document.body.appendChild(overlay);

  const close = () => overlay.remove();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.getElementById("share-modal-close").addEventListener("click", close);

  document.getElementById("share-download-btn").addEventListener("click", () => {
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    }, "image/png");
  });

  if (canShareNative) {
    document.getElementById("share-native-btn").addEventListener("click", () => {
      canvas.toBlob(async (blob) => {
        if (!blob) return;
        try {
          const file = new File([blob], filename, { type: "image/png" });
          if (navigator.canShare && !navigator.canShare({ files: [file] })) return;
          await navigator.share({ files: [file], title: "Travelify", text: shareText });
        } catch (e) {
          // Share sheet dismissed or unsupported — nothing to do.
        }
      }, "image/png");
    });
  }
}


function renderBadgesSection() {
  const badges = computeEarnedBadges(state.journal);
  const tiles = badges
    .map(
      (b) => `
      <button class="badge-tile ${b.earned ? "badge-earned" : "badge-locked"}" ${b.earned ? `data-share-badge="${b.id}"` : "disabled"} title="${escapeHtml(b.description)}">
        <div class="badge-tile-emoji">${b.earned ? b.emoji : "🔒"}</div>
        <div class="badge-tile-label">${escapeHtml(b.label)}</div>
      </button>`
    )
    .join("");
  return `
    <div class="badges-section">
      <div class="detail-label">🏅 Badges</div>
      <div class="badge-grid">${tiles}</div>
    </div>`;
}

function renderJournalPrivacy() {
  if (!isSupabaseConfigured() || !currentUser) return "";
  if (journalPublicError) return `<p class="rank-sub plan-error">${escapeHtml(journalPublicError)}</p>`;
  if (journalPublic === null) return "";
  return `<div class="privacy-card">
    <div>
      <div class="rank-name">Public journal</div>
      <div class="rank-sub">${journalPublic ? "People who follow you can see your trips in their Feed." : "Only you can see your trips. Turn on to share them with followers."}</div>
    </div>
    <button type="button" class="switch ${journalPublic ? "switch-on" : ""}" role="switch" aria-checked="${journalPublic}" aria-label="Public journal" id="journal-public-toggle"><span class="switch-knob"></span></button>
  </div>`;
}

function renderJournal() {
  const badgesSection = renderBadgesSection();
  const privacy = renderJournalPrivacy();
  if (state.journal.length === 0) {
    return `
      <h2 class="step-heading">Your Trip Journal</h2>
      ${privacy}
      ${badgesSection}
      <div class="empty">No trips planned yet. Match your first hotel to start your journal.</div>
    `;
  }
  const rows = state.journal
    .map((j, idx) => {
      const theme = THEME_META[j.themeKey];
      const color = j.score >= 75 ? "#2e7d4f" : j.score >= 50 ? "#b8860b" : "#c0392b";
      return `
      <li><button class="rank-row" data-open-trip="${idx}">
        <div class="rank-info">
          <div class="rank-name">${theme.emoji} ${escapeHtml(j.hotelName)}</div>
          <div class="rank-sub">${escapeHtml(j.city)} · ${theme.label} · ${timeAgo(j.timestamp)}</div>
        </div>
        <span class="badge" style="background:${color}">${j.score}%</span>
      </button></li>`;
    })
    .join("");

  return `
    <h2 class="step-heading">Your Trip Journal</h2>
    <p class="rank-sub">Tap a trip to open it again.</p>
    ${privacy}
    ${badgesSection}
    <ul class="rank-list">${rows}</ul>
  `;
}

// ---------- events ----------

function bindEvents() {
  root.querySelectorAll("[data-open-trip]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const j = state.journal[Number(btn.dataset.openTrip)];
      if (!j) return;
      const hotel = MOCK_HOTELS.find((h) => h.id === j.hotelId) || { id: j.hotelId || makeCustomId(), name: j.hotelName, city: j.city, tags: [] };
      selectedCity = j.city;
      selectedTheme = j.themeKey;
      chooseHotel(hotel, { record: false });
      window.scrollTo(0, 0);
    });
  });

  root.querySelectorAll("[data-follow]").forEach((btn) => {
    btn.addEventListener("click", () => toggleFollow(btn.dataset.follow, btn.dataset.followName));
  });
  root.querySelectorAll("[data-open-feed]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const j = feedEntries[Number(btn.dataset.openFeed)];
      if (!j) return;
      const hotel = MOCK_HOTELS.find((h) => h.id === j.hotelId) || { id: j.hotelId || makeCustomId(), name: j.hotelName, city: j.city, tags: [] };
      selectedCity = j.city;
      selectedTheme = j.themeKey;
      chooseHotel(hotel, { record: false });
      window.scrollTo(0, 0);
    });
  });
  const feedSignin = root.querySelector("[data-feed-signin]");
  if (feedSignin) feedSignin.addEventListener("click", () => openAuthModal("signin"));
  const journalToggle = document.getElementById("journal-public-toggle");
  if (journalToggle) journalToggle.addEventListener("click", toggleJournalPublic);

  root.querySelectorAll("[data-nav]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const target = btn.dataset.nav;
      if (target === "community") viewCommunity();
      else if (target === "feed") viewFeed();
      else if (target === "journal") {
        step = "journal";
        render();
      } else {
        step = planStep();
        render();
      }
      window.scrollTo(0, 0);
    });
  });

  const journalBtn = root.querySelector("[data-view-journal]");
  if (journalBtn) {
    journalBtn.addEventListener("click", () => {
      step = "journal";
      render();
    });
  }

  root.querySelectorAll("[data-step]").forEach((btn) => {
    btn.addEventListener("click", () => {
      step = btn.dataset.step;
      sharePlanError = null;
      sharePlanSuccess = false;
      planCheckError = null;
      render();
    });
  });

  root.querySelectorAll("[data-community-view]").forEach((btn) => {
    btn.addEventListener("click", () => setCommunityView(btn.dataset.communityView));
  });

  root.querySelectorAll("[data-vote]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const [planId, vote] = btn.dataset.vote.split("|");
      voteOnPlan(planId, Number(vote));
    });
  });
  root.querySelectorAll("[data-toggle-comments]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const id = btn.dataset.toggleComments;
      if (expandedComments.has(id)) expandedComments.delete(id);
      else expandedComments.add(id);
      render();
    });
  });
  root.querySelectorAll("[data-comment-input]").forEach((input) => {
    input.addEventListener("input", (e) => {
      commentDrafts[input.dataset.commentInput] = e.target.value;
    });
  });
  root.querySelectorAll("[data-comment-form]").forEach((form) => {
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      postComment(form.dataset.commentForm);
    });
  });
  root.querySelectorAll("[data-delete-comment]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const [planId, commentId] = btn.dataset.deleteComment.split("|");
      removeComment(planId, commentId);
    });
  });


  const planCheckNotesInput = document.getElementById("plan-check-notes");
  if (planCheckNotesInput) {
    planCheckNotesInput.addEventListener("input", (e) => {
      planCheckNotes = e.target.value;
    });
  }

  const sharePlanBtn = document.getElementById("share-plan-btn");
  if (sharePlanBtn) sharePlanBtn.addEventListener("click", shareMyPlan);

  const signInBtn = document.getElementById("sign-in-btn");
  if (signInBtn) signInBtn.addEventListener("click", () => openAuthModal("signin"));

  const signOutBtn = document.getElementById("sign-out-btn");
  if (signOutBtn) {
    signOutBtn.addEventListener("click", async () => {
      await signOut();
    });
  }

  root.querySelectorAll("[data-share-badge]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const badge = BADGE_DEFS.find((b) => b.id === btn.dataset.shareBadge);
      if (badge) openBadgeShareModal(badge);
    });
  });

  const planNewBtn = root.querySelector("[data-plan-new]");
  if (planNewBtn) planNewBtn.addEventListener("click", planNewTrip);

  root.querySelectorAll(".change-key-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      clearGeminiKey();
      openApiKeyModal(() => render());
    });
  });

  const checkPlanBtn = document.getElementById("check-plan-btn");
  if (checkPlanBtn) checkPlanBtn.addEventListener("click", checkMyPlan);

  root.querySelectorAll("[data-transport]").forEach((btn) => {
    btn.addEventListener("click", () => {
      if (planTransport === btn.dataset.transport) return;
      planTransport = btn.dataset.transport;
      planCheckResult = null;
      planCheckError = null;
      render();
    });
  });

  root.querySelectorAll("[data-photo-input]").forEach((input) => {
    input.addEventListener("change", () => {
      const [di, si] = input.dataset.photoInput.split("|").map(Number);
      const name = planCheckDays[di] && planCheckDays[di][si];
      if (name && input.files.length) addStopPhotos(name, input.files);
    });
  });
  root.querySelectorAll("[data-open-photo]").forEach((btn) => {
    btn.addEventListener("click", () => openPhotoLightbox(btn.dataset.openPhoto));
  });

  const addDayBtn = document.getElementById("add-day-btn");
  if (addDayBtn) addDayBtn.addEventListener("click", addPlanCheckDay);

  root.querySelectorAll("[data-remove-day]").forEach((btn) => {
    btn.addEventListener("click", () => removePlanCheckDay(Number(btn.dataset.removeDay)));
  });

  root.querySelectorAll("[data-add-stop-form]").forEach((form) => {
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const dayIndex = Number(form.dataset.addStopForm);
      const input = form.querySelector("input");
      addPlanCheckStop(dayIndex, input.value);
    });
  });

  root.querySelectorAll("[data-answer-tab]").forEach((btn) => {
    btn.addEventListener("click", () => {
      answerTab = btn.dataset.answerTab;
      render();
      window.scrollTo(0, 0);
    });
  });

  const showAllBtn = root.querySelector("[data-show-all-cities]");
  if (showAllBtn) {
    showAllBtn.addEventListener("click", () => {
      showAllCities = !showAllCities;
      render();
    });
  }

  root.querySelectorAll("[data-quick-add]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const [d, ni] = btn.dataset.quickAdd.split("|").map(Number);
      const name = currentSuggestions()[ni];
      if (name) addPlanCheckStop(d, name);
    });
  });

  root.querySelectorAll("[data-refresh-suggestions]").forEach((btn) => {
    btn.addEventListener("click", refreshSuggestions);
  });

  const shareDetails = root.querySelector("[data-share-details]");
  if (shareDetails) shareDetails.addEventListener("toggle", () => (shareOpen = shareDetails.open));

  root.querySelectorAll("[data-move-stop]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const [d, si, delta] = btn.dataset.moveStop.split("|").map(Number);
      movePlanCheckStop(d, si, delta);
    });
  });

  root.querySelectorAll("[data-apply-order]").forEach((btn) => {
    btn.addEventListener("click", () => applySuggestedOrder(Number(btn.dataset.applyOrder)));
  });

  root.querySelectorAll("[data-remove-stop]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const [dayIndex, stopIndex] = btn.dataset.removeStop.split("-").map(Number);
      removePlanCheckStop(dayIndex, stopIndex);
    });
  });

  root.querySelectorAll("[data-pick-city]").forEach((btn) => {
    btn.addEventListener("click", () => chooseCity(btn.dataset.pickCity));
  });

  root.querySelectorAll("[data-pick-hotel]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const hotel = MOCK_HOTELS.find((h) => h.id === btn.dataset.pickHotel);
      if (hotel) chooseHotel(hotel);
    });
  });

  root.querySelectorAll("[data-pick-theme]").forEach((btn) => {
    btn.addEventListener("click", () => chooseTheme(btn.dataset.pickTheme));
  });

  const cityInput = document.getElementById("city-input");
  if (cityInput) {
    cityInput.addEventListener("input", (e) => {
      cityQuery = e.target.value;
      const pos = e.target.selectionStart;
      render();
      const newInput = document.getElementById("city-input");
      if (newInput) {
        newInput.focus();
        newInput.setSelectionRange(pos, pos);
      }
    });
  }

  const showCustomBtn = document.getElementById("show-custom-hotel");
  if (showCustomBtn) {
    showCustomBtn.addEventListener("click", () => {
      showCustomHotelForm = true;
      render();
    });
  }

  const customForm = document.getElementById("custom-hotel-form");
  if (customForm) {
    customForm.addEventListener("submit", (e) => {
      e.preventDefault();
      const name = document.getElementById("custom-hotel-name").value.trim();
      if (!name) return;
      chooseHotel({ id: makeCustomId(), name, city: selectedCity, tags: [] });
    });
  }
}

restoreSession();
render();
loadHotelPhotos();
initAuth();
