// Hotelify — trip-fit matcher.
// Flow: pick a city -> pick a hotel in it -> pick a trip theme -> get a
// fit score + reasons for why that hotel suits that theme.
//
// Keeps a Trip Journal of past results — one mechanic borrowed deliberately
// from why Beli got trendy (research notes, not folklore): it frames each
// result as a personal travel memory rather than a one-off lookup (Beli
// succeeded partly by being a memory archive, not a review site). Beli's
// other big lever — peer trust over anonymous reviews — doesn't translate
// here: this is a solo planning tool with no social graph, so it's left
// out rather than faked with fabricated "friends."
//
// The fit score is a transparent rule-based heuristic over each hotel's
// own tags/tier (see data.js) — not a live AI/LLM call.

const STORAGE_KEY = "hotelify_tripmatch_v1";
const THEME_KEYS = ["romantic", "family", "business", "adventure", "relaxation"];

// Modern mark: a house built from separate green "stick" strokes (a
// roof chevron, two wall posts, a base) rather than a filled glyph —
// no background badge, just the line marks, instead of the 🏨 emoji.
const LOGO_SVG = `
  <svg width="30" height="30" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="logoGrad" x1="4" y1="6" x2="28" y2="26" gradientUnits="userSpaceOnUse">
        <stop offset="0" stop-color="#4ade80"/>
        <stop offset="1" stop-color="#047857"/>
      </linearGradient>
    </defs>
    <g stroke="url(#logoGrad)" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round">
      <path d="M5 17L16 6L27 17"/>
      <path d="M10 19.5V26"/>
      <path d="M22 19.5V26"/>
      <path d="M8 26H24"/>
    </g>
  </svg>
`;

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    return {
      journal: parsed.journal || [],
    };
  } catch (e) {
    return { journal: [] };
  }
}

function saveState() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}

let state = loadState();
let step = "city"; // city | hotel | theme | answer | journal
let cityQuery = "";
let selectedCity = null;
let selectedHotel = null;
let selectedTheme = null;
let showCustomHotelForm = false;

// AI plan check (Gemini) — the only place this app calls an LLM. The API
// key lives ONLY in localStorage, entered by the user at runtime in this
// running page — never written into a source file, so it never ends up
// in a git commit. If this app is ever hosted somewhere other than your
// own machine, anyone with dev tools open on that page could still read
// the key out of the request, same as any client-side API call — keep
// that in mind before deploying it publicly with a real key attached.
const GEMINI_KEY_STORAGE = "hotelify_gemini_key";
const GEMINI_MODEL = "gemini-3.8-flash";

// Customer-built day-by-day itinerary, checked for logistics (walking
// distance, traffic, pacing) by AI rather than generated by it. Customers
// add/remove days freely — no fixed cap.
let planCheckDays = [[]];
let planCheckNotes = "";
let planCheckLoading = false;
let planCheckError = null;
let planCheckResult = null;

// ---------- accounts (Supabase) ----------
// Falls back to the existing guest/localStorage journal untouched when
// config.js still has placeholder values (see auth.js).
let currentUser = null;
let journalSource = "guest"; // "guest" | "account"
let authError = null;
let authLoading = false;

// Sharing a checked plan (stops + notes) publicly to the community feed.
let sharePlanLoading = false;
let sharePlanError = null;
let sharePlanSuccess = false;
let communityPlans = [];
let communityLoading = false;
let communityError = null;

async function initAuth() {
  if (!isSupabaseConfigured()) return;
  currentUser = await getCurrentUser();
  if (currentUser) await loadAccountJournal();
  render();
  supabaseClient.auth.onAuthStateChange(async (_event, session) => {
    currentUser = session ? session.user : null;
    if (currentUser) {
      await loadAccountJournal();
    } else {
      journalSource = "guest";
      state = loadState();
    }
    render();
  });
}

async function loadAccountJournal() {
  try {
    state.journal = await fetchJournalEntries(currentUser.id);
    journalSource = "account";
  } catch (e) {
    console.error("Failed to load account journal", e);
  }
}

// ---------- data helpers ----------

function uniqueCities() {
  return [...new Set(MOCK_HOTELS.map((h) => h.city))].sort();
}

function hotelsInCity(city) {
  const c = city.trim().toLowerCase();
  return MOCK_HOTELS.filter((h) => h.city.toLowerCase() === c);
}

function makeCustomId() {
  return "custom-" + Date.now() + "-" + Math.floor(Math.random() * 1000);
}

// Fallback only, for hotels with no known official site (custom/manual
// entries) — a general search rather than a fabricated booking link.
// Any hotel with a real `website` on file books there directly instead.
function hotelSearchFallbackUrl(h) {
  const query = encodeURIComponent([h.name, h.city, h.country].filter(Boolean).join(" "));
  return `https://www.google.com/travel/hotels?q=${query}`;
}

// Links to live Google Maps directions from the city's airport rather
// than a hardcoded fare/time — this app has no real transit-pricing API,
// so an invented "$12, 35 min" would just be a guess dressed up as fact.
// Google Maps computes current, real transit vs. driving estimates.
function gettingThereUrls(h) {
  const destination = encodeURIComponent(h.address || [h.name, h.city, h.country].filter(Boolean).join(", "));
  const origin = encodeURIComponent(`${h.city} airport`);
  return {
    transit: `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=transit`,
    driving: `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=driving`,
  };
}

// ---------- Gemini trip planning ----------

function getGeminiKey() {
  return localStorage.getItem(GEMINI_KEY_STORAGE) || "";
}

function setGeminiKey(key) {
  localStorage.setItem(GEMINI_KEY_STORAGE, key.trim());
}

function clearGeminiKey() {
  localStorage.removeItem(GEMINI_KEY_STORAGE);
}

// Newest model first; falls through to older Flash models when Google
// answers 503 (overloaded) or 429 (rate-limited) for the current one.
const GEMINI_FALLBACK_MODELS = [GEMINI_MODEL, "gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.5-flash"];

async function callGemini(prompt, { json = false } = {}) {
  const key = getGeminiKey();
  let lastError = null;
  const payload = { contents: [{ parts: [{ text: prompt }] }] };
  if (json) payload.generationConfig = { responseMimeType: "application/json" };

  for (const model of GEMINI_FALLBACK_MODELS) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`;
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const body = await res.json().catch(() => null);
      lastError = new Error(body && body.error && body.error.message ? body.error.message : `Request failed (${res.status})`);
      if (res.status === 503 || res.status === 429) continue;
      throw lastError;
    }

    const data = await res.json();
    const text = data?.candidates?.[0]?.content?.parts?.map((p) => p.text).join("") || "";
    if (!text) throw new Error("The AI returned an empty response.");
    return text.trim();
  }
  throw lastError;
}

// Reviews a customer-WRITTEN day-by-day stop list for logistics problems
// (too much walking/backtracking, likely bad traffic between far-apart
// stops, an overpacked or too-sparse day) and estimates calories burned
// per day from the walking it implies — this app's only AI call.
async function evaluateCustomItinerary(hotel, themeKey, days) {
  const theme = THEME_META[themeKey];
  const dayLines = days
    .map((stops, i) => `Day ${i + 1}: ${stops.length ? stops.join(" -> ") : "(no stops added)"}`)
    .join("\n");
  const prompt = `You are a practical, concise travel-logistics reviewer, not a trip planner. A traveler staying at ${hotel.name} in ${hotel.city}${hotel.country ? ", " + hotel.country : ""} on a ${theme.label}-themed trip has drafted this day-by-day list of places they want to visit, in the order listed:\n${dayLines}\n\nGive feedback on EVERY stop and on EVERY leg between consecutive stops (a leg is the trip from one stop to the next, in order).\n- For each stop: a verdict, a short feedback line, and 1-3 keywords describing it (pick from words like luxurious, fun, budget-friendly, romantic, historic, scenic, relaxing, foodie, cultural, active, shopping, nightlife, family-friendly, touristy, crowded — or another short fitting word).\n- For each leg: a verdict and feedback covering distance, walking vs taxi/transit, and likely traffic.\n- For each day: estimated total walking distance (km) and calories burned (kcal) for an average adult, assuming they walk between nearby stops and use taxi/transit for far-apart ones (rough estimates).\n\nKeep feedback SHORT (under 15 words) when something is fine. Use up to ~40 words only when a change is needed, and say specifically what to change (reorder, drop, split the day, take a taxi). Don't invent problems.\n\nRespond with ONLY a JSON object of exactly this shape. "days" has one entry per day in order (${days.length} total); each day's "stops" has one entry per stop in order, and "legs" has one entry per consecutive pair (stops minus one; empty array if 0 or 1 stops):\n{"days":[{"stops":[{"verdict":"good" or "review","feedback":"...","keywords":["..."]}],"legs":[{"verdict":"good" or "review","feedback":"..."}],"walkingKm":number,"kcal":number}],"summary":"1-2 sentence overall take","keywords":["2-4 keywords describing the whole plan"],"totalKcal":number}\nUse "good" when it works as written and "review" when it's worth looking at again.`;
  const text = await callGemini(prompt, { json: true });
  try {
    const parsed = JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g, ""));
    if (parsed && Array.isArray(parsed.days)) return parsed;
  } catch (e) {
    // fall through to raw text
  }
  return { raw: text };
}

function hotelSubtitle(h) {
  return [h.city, h.country].filter(Boolean).join(", ");
}

// ---------- fit scoring ----------

function evaluateFit(hotel, themeKey) {
  const theme = THEME_META[themeKey];
  const tags = hotel.tags || [];
  const matchedTags = tags.filter((t) => theme.tags.includes(t));
  let score = 45 + matchedTags.length * 13;
  const tierMatch = hotel.tier && theme.tierBoost.includes(hotel.tier);
  if (tierMatch) score += 12;
  score = Math.max(5, Math.min(98, Math.round(score)));

  const reasons = matchedTags.map((t) => theme.tagReasons[t]).filter(Boolean);
  if (tierMatch) {
    reasons.push(`a ${TIER_META[hotel.tier].label.toLowerCase()} property, well suited to a ${theme.label.toLowerCase()} trip`);
  }
  if (reasons.length === 0) {
    reasons.push(
      `no specific ${theme.label.toLowerCase()}-oriented details on file for this hotel, so this is a lower-confidence match`
    );
  }

  const verdict = score >= 75 ? "Great match" : score >= 50 ? "Decent match" : "Not an ideal match";
  const color = score >= 75 ? "#2e7d4f" : score >= 50 ? "#b8860b" : "#c0392b";
  return { score, reasons: reasons.slice(0, 4), verdict, color };
}

// ---------- badges ----------
// Self-paced achievements computed from journal history — work the same
// whether the journal is guest/localStorage or account-synced, since
// they only read already-loaded `state.journal` fields.

const BADGE_DEFS = [
  { id: "first-trip", emoji: "🧳", label: "First Trip", description: "Matched your first hotel.", check: (s) => s.total >= 1 },
  { id: "city-hopper", emoji: "🗺️", label: "City Hopper", description: "Matched hotels in 5+ cities.", check: (s) => s.cityCount >= 5 },
  { id: "world-explorer", emoji: "🌍", label: "World Explorer", description: "Matched hotels in 15+ cities.", check: (s) => s.cityCount >= 15 },
  { id: "perfect-match", emoji: "🎯", label: "Perfect Match", description: "Scored a 90%+ fit.", check: (s) => s.maxScore >= 90 },
  { id: "romantic", emoji: "💕", label: "Hopeless Romantic", description: "3+ Romantic trip matches.", check: (s) => (s.themeCounts.romantic || 0) >= 3 },
  { id: "family", emoji: "👨‍👩‍👧", label: "Family Planner", description: "3+ Family trip matches.", check: (s) => (s.themeCounts.family || 0) >= 3 },
  { id: "business", emoji: "💼", label: "Road Warrior", description: "3+ Business trip matches.", check: (s) => (s.themeCounts.business || 0) >= 3 },
  { id: "adventure", emoji: "🧗", label: "Thrill Seeker", description: "3+ Adventure trip matches.", check: (s) => (s.themeCounts.adventure || 0) >= 3 },
  { id: "relaxation", emoji: "🧘", label: "Zen Master", description: "3+ Relaxation trip matches.", check: (s) => (s.themeCounts.relaxation || 0) >= 3 },
  { id: "decade-club", emoji: "📅", label: "Decade Club", description: "10+ trips matched total.", check: (s) => s.total >= 10 },
];

function computeJournalStats(journal) {
  const cities = new Set(journal.map((j) => j.city));
  const themeCounts = {};
  let maxScore = 0;
  journal.forEach((j) => {
    themeCounts[j.themeKey] = (themeCounts[j.themeKey] || 0) + 1;
    if (j.score > maxScore) maxScore = j.score;
  });
  return { total: journal.length, cityCount: cities.size, themeCounts, maxScore };
}

function computeEarnedBadges(journal) {
  const stats = computeJournalStats(journal);
  return BADGE_DEFS.map((b) => ({ ...b, earned: b.check(stats) }));
}

// ---------- journal ----------

function recordTripMatch(entry) {
  state.journal.unshift(entry);
  if (journalSource === "account" && currentUser) {
    insertJournalEntry(currentUser.id, entry).catch((e) => {
      console.error("Failed to sync journal entry to account", e);
    });
  } else {
    saveState();
  }
}

// ---------- navigation ----------

function chooseCity(city) {
  selectedCity = city;
  selectedHotel = null;
  showCustomHotelForm = false;
  step = "theme";
  render();
}

function chooseTheme(themeKey) {
  selectedTheme = themeKey;
  showCustomHotelForm = false;
  step = "hotel";
  render();
}

function chooseHotel(hotel) {
  selectedHotel = hotel;
  sharePlanError = null;
  sharePlanSuccess = false;
  planCheckDays = [[]];
  planCheckNotes = "";
  planCheckResult = null;
  planCheckError = null;
  const fit = evaluateFit(hotel, selectedTheme);
  recordTripMatch({
    id: "trip-" + Date.now(),
    hotelId: hotel.id,
    city: hotel.city,
    hotelName: hotel.name,
    themeKey: selectedTheme,
    score: fit.score,
    verdict: fit.verdict,
    timestamp: Date.now(),
  });
  step = "answer";
  render();
}

function planNewTrip() {
  selectedCity = null;
  selectedHotel = null;
  selectedTheme = null;
  cityQuery = "";
  showCustomHotelForm = false;
  sharePlanError = null;
  sharePlanSuccess = false;
  planCheckDays = [[]];
  planCheckNotes = "";
  planCheckResult = null;
  planCheckError = null;
  step = "city";
  render();
}

function formatPlanCheckForSharing() {
  const dayLines = planCheckDays
    .map((stops, i) => `Day ${i + 1}: ${stops.length ? stops.join(" -> ") : "(no stops added)"}`)
    .join("\n");
  const notes = planCheckNotes.trim();
  let aiCheck = "";
  if (planCheckResult && planCheckResult.raw) {
    aiCheck = planCheckResult.raw.trim();
  } else if (planCheckResult) {
    const tag = (v) => (v === "good" ? "looks good" : "worth another look");
    aiCheck = planCheckResult.days
      .map((d, i) => {
        const lines = [`Day ${i + 1} (~${d.walkingKm} km, ~${d.kcal} kcal)`];
        (d.stops || []).forEach((st, si) => {
          const kw = st.keywords && st.keywords.length ? ` [${st.keywords.join(", ")}]` : "";
          lines.push(`  ${planCheckDays[i] ? planCheckDays[i][si] : "Stop"}${kw} - ${tag(st.verdict)}: ${st.feedback}`);
          const leg = (d.legs || [])[si];
          if (leg && si < (d.stops || []).length - 1) lines.push(`    -> next: ${tag(leg.verdict)}: ${leg.feedback}`);
        });
        return lines.join("\n");
      })
      .join("\n");
    if (planCheckResult.keywords && planCheckResult.keywords.length) aiCheck += `\nPlan vibe: ${planCheckResult.keywords.join(", ")}`;
    if (planCheckResult.summary) aiCheck += `\n${planCheckResult.summary}`;
    if (planCheckResult.totalKcal) aiCheck += `\nTotal: ~${planCheckResult.totalKcal} kcal`;
  }
  let text = dayLines;
  if (notes) text += `\n\nNotes: ${notes}`;
  if (aiCheck) text += `\n\nAI Check: ${aiCheck}`;
  return text;
}

async function shareMyPlan() {
  if (!currentUser) {
    openAuthModal("signin");
    return;
  }
  const hasAnyStops = planCheckDays.some((d) => d.length > 0);
  if (!hasAnyStops) return;
  sharePlanLoading = true;
  sharePlanError = null;
  render();
  try {
    const fit = evaluateFit(selectedHotel, selectedTheme);
    const username = currentUser.user_metadata && currentUser.user_metadata.username ? currentUser.user_metadata.username : currentUser.email;
    await sharePlanPublicly(currentUser.id, username, {
      hotelName: selectedHotel.name,
      city: selectedHotel.city,
      themeKey: selectedTheme,
      score: fit.score,
      planText: formatPlanCheckForSharing(),
    });
    sharePlanSuccess = true;
  } catch (e) {
    sharePlanError = e.message || "Couldn't share your plan.";
  }
  sharePlanLoading = false;
  render();
}

async function viewCommunity() {
  step = "community";
  communityLoading = true;
  communityError = null;
  render();
  try {
    communityPlans = await fetchPublicPlans(50);
  } catch (e) {
    communityError = e.message || "Couldn't load community plans.";
  }
  communityLoading = false;
  render();
}

function addPlanCheckStop(dayIndex, stop) {
  const trimmed = stop.trim();
  if (!trimmed) return;
  planCheckDays[dayIndex].push(trimmed);
  render();
}

function removePlanCheckStop(dayIndex, stopIndex) {
  planCheckDays[dayIndex].splice(stopIndex, 1);
  render();
}

function addPlanCheckDay() {
  planCheckDays.push([]);
  render();
}

function removePlanCheckDay(dayIndex) {
  if (planCheckDays.length <= 1) return;
  planCheckDays.splice(dayIndex, 1);
  render();
}

async function checkMyPlan() {
  if (!getGeminiKey()) {
    openApiKeyModal(checkMyPlan);
    return;
  }
  planCheckLoading = true;
  planCheckError = null;
  render();
  try {
    planCheckResult = await evaluateCustomItinerary(selectedHotel, selectedTheme, planCheckDays);
  } catch (e) {
    planCheckError = e.message || "Something went wrong checking the plan.";
  }
  planCheckLoading = false;
  render();
}

// ---------- rendering ----------

const root = document.getElementById("app");

function escapeHtml(s) {
  const div = document.createElement("div");
  div.textContent = s;
  return div.innerHTML;
}

function timeAgo(ms) {
  const hours = (Date.now() - ms) / 3600000;
  if (hours < 1) return "just now";
  if (hours < 24) return Math.round(hours) + "h ago";
  return Math.round(hours / 24) + "d ago";
}

function renderAccountControl() {
  if (!isSupabaseConfigured()) return "";
  if (currentUser) {
    const username = currentUser.user_metadata && currentUser.user_metadata.username ? currentUser.user_metadata.username : currentUser.email;
    return `<button class="journal-badge" id="sign-out-btn" title="Sign out">👤 ${escapeHtml(username)}</button>`;
  }
  return `<button class="journal-badge" id="sign-in-btn">Sign In</button>`;
}

function render() {
  root.classList.toggle("wide", step === "answer");
  root.innerHTML = `
    <header class="topbar">
      <div class="topbar-row">
        <button class="brand brand-btn" data-plan-new title="Start a new trip">${LOGO_SVG} Hotelify</button>
        <div class="header-right">
          ${renderAccountControl()}
          ${isSupabaseConfigured() ? `<button class="journal-badge" id="view-community-btn" title="Community Plans">🌍 Community</button>` : ""}
          <button class="journal-badge" data-view-journal title="Your Trip Journal">📖 Journal</button>
        </div>
      </div>
    </header>
    <main>${renderStep()}</main>
  `;
  bindEvents();
}

function renderStep() {
  if (step === "city") return renderCityStep();
  if (step === "theme") return renderThemeStep();
  if (step === "hotel") return renderHotelStep();
  if (step === "answer") return renderAnswerStep();
  if (step === "journal") return renderJournal();
  if (step === "community") return renderCommunityStep();
  return "";
}

function renderCommunityStep() {
  const header = `
    <button class="icon-btn back-btn" data-step="city">← Back</button>
    <h2 class="step-heading">Community Plans</h2>
    <p class="rank-sub">Real itineraries written by other travelers.</p>
  `;

  if (communityLoading) return header + `<div class="empty">Loading…</div>`;
  if (communityError) return header + `<div class="empty">${escapeHtml(communityError)}</div>`;
  if (communityPlans.length === 0) return header + `<div class="empty">No shared plans yet — be the first!</div>`;

  const cards = communityPlans
    .map((p) => {
      const theme = THEME_META[p.theme_key];
      return `
      <li class="plan-card">
        <div class="rank-name">${theme ? theme.emoji : ""} ${escapeHtml(p.hotel_name)}</div>
        <div class="rank-sub">${escapeHtml(p.city)} · by ${escapeHtml(p.username)} · ${p.score}% ${theme ? theme.label : ""} fit</div>
        <p class="rank-sub plan-card-text">${escapeHtml(p.plan_text)}</p>
      </li>`;
    })
    .join("");

  return header + `<ul class="rank-list">${cards}</ul>`;
}

function renderCityStep() {
  const rawQuery = cityQuery.trim();
  const q = rawQuery.toLowerCase();
  const allCities = uniqueCities();
  const cities = allCities.filter((c) => (q ? c.toLowerCase().includes(q) : true));
  const rows = cities
    .slice(0, 30)
    .map((c) => `<button class="rank-row city-row" data-pick-city="${escapeHtml(c)}">${escapeHtml(c)}</button>`)
    .join("");

  const exactMatch = allCities.some((c) => c.toLowerCase() === q);
  const useTypedCity =
    rawQuery && !exactMatch
      ? `<button class="pill-btn ghost use-typed-city" data-pick-city="${escapeHtml(rawQuery)}">Use "${escapeHtml(rawQuery)}" as my city</button>`
      : "";

  return `
    <h2 class="step-heading">Where are you traveling?</h2>
    <div class="search-wrap">
      <input id="city-input" type="text" placeholder="Search a city…" value="${escapeHtml(cityQuery)}" />
    </div>
    <div class="rank-list">${rows || (rawQuery ? "" : `<div class="empty">No cities match. Try a different search.</div>`)}</div>
    ${useTypedCity}
  `;
}

function renderThemeStep() {
  const cards = THEME_KEYS.map((key) => {
    const t = THEME_META[key];
    return `
      <button class="theme-card" data-pick-theme="${key}">
        <div class="theme-emoji">${t.emoji}</div>
        <div class="theme-label">${t.label}</div>
        <div class="rank-sub">${t.blurb}</div>
      </button>`;
  }).join("");

  return `
    <button class="icon-btn back-btn" data-step="city">← Change city</button>
    <h2 class="step-heading">What's the vibe for this trip?</h2>
    <p class="rank-sub">Traveling to ${escapeHtml(selectedCity)}</p>
    <div class="theme-grid">${cards}</div>
  `;
}

function renderHotelStep() {
  const theme = THEME_META[selectedTheme];
  const hotels = hotelsInCity(selectedCity)
    .map((h) => ({ hotel: h, fit: evaluateFit(h, selectedTheme) }))
    .sort((a, b) => b.fit.score - a.fit.score);

  const rows = hotels
    .map(
      ({ hotel: h, fit }) => `
      <button class="rank-row hotel-row" data-pick-hotel="${h.id}">
        <div class="rank-info">
          <div class="rank-name">${escapeHtml(h.name)}</div>
          <div class="rank-sub">${escapeHtml(TIER_META[h.tier].label)}${h.tags && h.tags.length ? " · " + h.tags.slice(0, 3).join(", ") : ""}</div>
        </div>
        <span class="badge" style="background:${fit.color}">${fit.score}%</span>
      </button>`
    )
    .join("");

  const customForm = showCustomHotelForm
    ? `
    <form id="custom-hotel-form" class="custom-add">
      <input id="custom-hotel-name" type="text" placeholder="Hotel name" required />
      <button type="submit" class="pill-btn">Use this hotel</button>
    </form>`
    : `<button class="pill-btn ghost" id="show-custom-hotel">Can't find it? Enter it manually</button>`;

  return `
    <button class="icon-btn back-btn" data-step="theme">← Change theme</button>
    <h2 class="step-heading">Choose your hotel in ${escapeHtml(selectedCity)}</h2>
    <p class="rank-sub">${theme.emoji} ${theme.label} trip · scores show fit for this vibe</p>
    <div class="rank-list">${rows || `<div class="empty">No hotels on file for ${escapeHtml(selectedCity)} yet.</div>`}</div>
    <div class="custom-add-wrap">${customForm}</div>
  `;
}

function renderAnswerStep() {
  const hotel = selectedHotel;
  const theme = THEME_META[selectedTheme];
  const fit = evaluateFit(hotel, selectedTheme);

  const reasonsList = fit.reasons.map((r) => `<li>${escapeHtml(r)}</li>`).join("");

  const addressBlock = hotel.address
    ? `
    <div class="detail-section">
      <div class="detail-label">Address</div>
      <div class="rank-sub">${escapeHtml(hotel.address)}</div>
    </div>`
    : "";

  const nearbyBlock =
    hotel.nearby && hotel.nearby.length
      ? `
    <div class="detail-section">
      <div class="detail-label">Nearby</div>
      <div class="rank-sub">${hotel.nearby.map(escapeHtml).join(" · ")}</div>
    </div>`
      : "";

  const gt = gettingThereUrls(hotel);
  const gettingThere = `
    <div class="detail-section">
      <div class="detail-label">Getting there from the airport</div>
      <div class="detail-links">
        <a class="pill-btn ghost" href="${gt.transit}" target="_blank" rel="noopener">🚆 Economical (transit)</a>
        <a class="pill-btn ghost" href="${gt.driving}" target="_blank" rel="noopener">🚕 Fastest (drive/taxi)</a>
      </div>
      <p class="rank-sub getting-there-note">Opens live Google Maps directions — real current times/fares, not a guess.</p>
    </div>`;

  const links = hotel.website
    ? `
    <div class="detail-links">
      <a class="pill-btn" href="${hotel.website}" target="_blank" rel="noopener">📅 Book on Official Site</a>
    </div>`
    : `
    <div class="detail-links">
      <a class="pill-btn ghost" href="${hotelSearchFallbackUrl(hotel)}" target="_blank" rel="noopener">🔍 Search for this hotel</a>
    </div>
    <p class="rank-sub getting-there-note">No official site on file for this hotel — this opens a general search instead.</p>`;

  return `
    <button class="icon-btn back-btn" data-step="hotel">← Change hotel</button>
    <div class="answer-header">
      <span class="badge answer-badge" style="background:${fit.color}">${fit.score}%</span>
      <div>
        <div class="answer-verdict">${fit.verdict}</div>
        <div class="rank-sub">${theme.emoji} ${theme.label} trip at ${escapeHtml(hotel.name)}</div>
      </div>
    </div>

    <ul class="reasons-list">${reasonsList}</ul>

    ${addressBlock}
    ${nearbyBlock}
    ${gettingThere}
    ${links}

    ${renderPlanCheckSection()}

    <div class="detail-actions">
      <button class="pill-btn ghost" data-step="theme">Try a different theme</button>
      <button class="pill-btn ghost" data-step="hotel">Try a different hotel</button>
    </div>
    <p class="rank-sub journal-note">Saved to your Trip Journal</p>
  `;
}

function renderPlanCheckSection() {
  const structured = planCheckResult && !planCheckResult.raw ? planCheckResult : null;

  const verdictClass = (v) => (v === "good" ? "feedback-good" : "feedback-review");
  const keywordChips = (kws) =>
    kws && kws.length ? `<div class="kw-row">${kws.map((k) => `<span class="kw-chip">${escapeHtml(String(k))}</span>`).join("")}</div>` : "";

  const stopFeedback = (st) =>
    st
      ? `<div class="feedback-card ${verdictClass(st.verdict)}">
          <div class="feedback-text">${st.verdict === "good" ? "✅" : "⚠️"} ${escapeHtml(st.feedback || "")}</div>
          ${keywordChips(st.keywords)}
        </div>`
      : "";

  const legFeedback = (leg) =>
    leg ? `<div class="feedback-card feedback-leg ${verdictClass(leg.verdict)}"><div class="feedback-text">${leg.verdict === "good" ? "✅" : "⚠️"} ${escapeHtml(leg.feedback || "")}</div></div>` : "";

  const dayBlocks = planCheckDays
    .map((stops, i) => {
      const dr = structured && structured.days[i];
      const removeBtn = planCheckDays.length > 1 ? `<button type="button" class="icon-btn" data-remove-day="${i}">Remove day</button>` : "";

      const rows = stops
        .map((s, si) => {
          const stopRow = `
          <div class="plan-row">
            <div class="plan-col"><span class="stop-chip">${escapeHtml(s)} <button type="button" class="stop-chip-remove" data-remove-stop="${i}-${si}">✕</button></span></div>
            <div class="feedback-col">${planCheckLoading ? "" : stopFeedback(dr && dr.stops && dr.stops[si])}</div>
          </div>`;
          const hasNext = si < stops.length - 1;
          const legRow = hasNext
            ? `
          <div class="plan-row plan-leg-row">
            <div class="plan-col plan-leg">↓ ${escapeHtml(s)} → ${escapeHtml(stops[si + 1])}</div>
            <div class="feedback-col">${planCheckLoading ? "" : legFeedback(dr && dr.legs && dr.legs[si])}</div>
          </div>`
            : "";
          return stopRow + legRow;
        })
        .join("");

      const dayAnyReview = dr && [...(dr.stops || []), ...(dr.legs || [])].some((x) => x && x.verdict !== "good");
      const dayStats =
        dr && !planCheckLoading
          ? `<div class="feedback-card feedback-day ${dayAnyReview ? "feedback-review" : "feedback-good"}"><div class="feedback-stats">Day ${i + 1}: ~${escapeHtml(String(dr.walkingKm))} km walking · ~${escapeHtml(String(dr.kcal))} kcal</div></div>`
          : "";

      return `
      <div class="plan-check-day">
        <div class="plan-day-label">Day ${i + 1} ${removeBtn}</div>
        ${stops.length ? rows : `<p class="rank-sub">No stops added yet.</p>`}
        <div class="plan-row">
          <div class="plan-col">
            <form class="custom-add" data-add-stop-form="${i}">
              <input type="text" placeholder="Add a place (e.g. Eiffel Tower)" />
              <button type="submit" class="pill-btn ghost">Add</button>
            </form>
          </div>
          <div class="feedback-col">${dayStats}</div>
        </div>
      </div>`;
    })
    .join("");

  let resultBlock = "";
  if (planCheckError) {
    resultBlock = `
      <p class="rank-sub plan-error">${escapeHtml(planCheckError)}</p>
      <button class="icon-btn change-key-btn">Change API key</button>`;
  } else if (planCheckResult && planCheckResult.raw) {
    resultBlock = `<p class="rank-sub ai-plan-text">${escapeHtml(planCheckResult.raw)}</p>`;
  } else if (structured && !planCheckLoading) {
    resultBlock = `
      <div class="plan-summary">
        ${keywordChips(structured.keywords)}
        ${structured.summary ? `<div>${escapeHtml(structured.summary)}</div>` : ""}
        ${structured.totalKcal ? `<div class="plan-summary-total">Total: ~${escapeHtml(String(structured.totalKcal))} kcal over ${planCheckDays.length} day${planCheckDays.length > 1 ? "s" : ""} (rough estimate)</div>` : ""}
      </div>`;
  }

  const hasAnyStops = planCheckDays.some((d) => d.length > 0);

  const shareBlock = isSupabaseConfigured()
    ? sharePlanSuccess
      ? `<p class="rank-sub">🎉 Shared with the community! Check the 🌍 Community tab.</p>`
      : `
      <div class="detail-section">
        <div class="detail-label">Notes</div>
        <textarea id="plan-check-notes" class="plan-textarea" rows="3" placeholder="Any tips for other travelers following this plan?">${escapeHtml(planCheckNotes)}</textarea>
        ${sharePlanError ? `<p class="rank-sub plan-error">${escapeHtml(sharePlanError)}</p>` : ""}
        <button class="pill-btn ghost" id="share-plan-btn" ${sharePlanLoading || !hasAnyStops ? "disabled" : ""}>${sharePlanLoading ? "Sharing…" : "🌍 Share with the Community"}</button>
        ${!currentUser ? `<p class="rank-sub">Sign in to share your plan publicly.</p>` : ""}
      </div>`
    : "";

  return `
  <div class="detail-section plan-section">
    <div class="detail-label">📍 Check My Plan</div>
    <p class="rank-sub">Add the places you actually want to visit each day — AI checks whether it's realistic (too much walking, bad traffic, overpacked days) and estimates the calories you'll burn each day.</p>
    ${dayBlocks}
    <button type="button" class="pill-btn ghost" id="add-day-btn">+ Add Day</button>
    <button class="pill-btn" id="check-plan-btn" ${planCheckLoading || !hasAnyStops ? "disabled" : ""}>${planCheckLoading ? "Checking…" : "🔍 Check My Plan"}</button>
    ${resultBlock}
    ${shareBlock}
  </div>`;
}

// ---------- auth modal ----------

function openAuthModal(initialMode) {
  let mode = initialMode || "signin";

  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";

  function paint() {
    overlay.innerHTML = `
      <div class="share-modal">
        <button class="icon-btn share-modal-close" id="auth-modal-close">✕ Close</button>
        <h3 class="step-heading">${mode === "signin" ? "Sign In" : "Create Account"}</h3>
        <form id="auth-form" class="custom-add" style="flex-direction:column; gap:10px;">
          ${mode === "signup" ? `<input id="auth-username" type="text" placeholder="Username" required autocomplete="username" />` : ""}
          <input id="auth-email" type="email" placeholder="Email" required autocomplete="email" />
          <input id="auth-password" type="password" placeholder="Password" required autocomplete="${mode === "signin" ? "current-password" : "new-password"}" minlength="6" />
          <button type="submit" class="pill-btn" ${authLoading ? "disabled" : ""}>${authLoading ? "Please wait…" : mode === "signin" ? "Sign In" : "Create Account"}</button>
        </form>
        ${authError ? `<p class="rank-sub plan-error">${escapeHtml(authError)}</p>` : ""}
        <p class="rank-sub share-modal-note">
          ${mode === "signin" ? "New here?" : "Already have an account?"}
          <a href="#" id="auth-switch-mode">${mode === "signin" ? "Create an account" : "Sign in"}</a>
        </p>
      </div>
    `;

    document.getElementById("auth-modal-close").addEventListener("click", () => overlay.remove());
    document.getElementById("auth-switch-mode").addEventListener("click", (e) => {
      e.preventDefault();
      mode = mode === "signin" ? "signup" : "signin";
      authError = null;
      paint();
    });
    document.getElementById("auth-form").addEventListener("submit", async (e) => {
      e.preventDefault();
      const email = document.getElementById("auth-email").value.trim();
      const password = document.getElementById("auth-password").value;
      const username = mode === "signup" ? document.getElementById("auth-username").value.trim() : null;
      authLoading = true;
      authError = null;
      paint();
      try {
        if (mode === "signup") {
          await signUp(email, password, username);
        } else {
          await signIn(email, password);
        }
        authLoading = false;
        overlay.remove();
      } catch (err) {
        authLoading = false;
        authError = err.message || "Something went wrong.";
        paint();
      }
    });
  }

  paint();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) overlay.remove();
  });
  document.body.appendChild(overlay);
}

// ---------- API key modal ----------
// Shared by every AI feature (Plan the Trip, Check My Plan) so the key
// prompt always appears the same way regardless of which one triggered
// it, instead of being embedded inline in just one feature's section.

function openApiKeyModal(onSaved) {
  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";
  overlay.innerHTML = `
    <div class="share-modal">
      <button class="icon-btn share-modal-close" id="key-modal-close">✕ Close</button>
      <h3 class="step-heading">AI API key</h3>
      <p class="rank-sub">Stored only in this browser's localStorage — never written to a file, never committed to git. Get a key at <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener">aistudio.google.com/apikey</a>.</p>
      <form id="api-key-form" class="custom-add">
        <input id="api-key-input" type="password" placeholder="Paste your AI API key" required autocomplete="off" />
        <button type="submit" class="pill-btn">Save</button>
      </form>
    </div>`;
  document.body.appendChild(overlay);

  const close = () => overlay.remove();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.getElementById("key-modal-close").addEventListener("click", close);
  document.getElementById("api-key-form").addEventListener("submit", (e) => {
    e.preventDefault();
    const key = document.getElementById("api-key-input").value.trim();
    if (!key) return;
    setGeminiKey(key);
    close();
    onSaved();
  });
}

// ---------- shareable match card ----------
// Renders the fit result as a downloadable/shareable PNG (canvas, drawn
// client-side — no server, no image-generation API). This is the app's
// main growth lever: the shared image doubles as an ad for Hotelify.

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-+|-+$)/g, "") || "hotel";
}

function wrapCenteredText(ctx, text, x, y, maxWidth, lineHeight, maxLines) {
  const words = text.split(" ");
  let line = "";
  const lines = [];
  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + " ";
    if (ctx.measureText(testLine).width > maxWidth && n > 0) {
      lines.push(line.trim());
      line = words[n] + " ";
    } else {
      line = testLine;
    }
  }
  lines.push(line.trim());
  const clipped = maxLines ? lines.slice(0, maxLines) : lines;
  clipped.forEach((l, i) => ctx.fillText(l, x, y + i * lineHeight));
  return clipped.length;
}

function drawShareLogo(ctx, x, y, size) {
  const scale = size / 32;
  ctx.save();
  ctx.translate(x, y);
  ctx.scale(scale, scale);
  const grad = ctx.createLinearGradient(4, 6, 28, 26);
  grad.addColorStop(0, "#4ade80");
  grad.addColorStop(1, "#047857");
  ctx.strokeStyle = grad;
  ctx.lineWidth = 2.75;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  ctx.beginPath();
  ctx.moveTo(5, 17);
  ctx.lineTo(16, 6);
  ctx.lineTo(27, 17);
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(10, 19.5);
  ctx.lineTo(10, 26);
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(22, 19.5);
  ctx.lineTo(22, 26);
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(8, 26);
  ctx.lineTo(24, 26);
  ctx.stroke();
  ctx.restore();
}

function buildBadgeCanvas(badge) {
  const W = 1080;
  const H = 1920;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  const font = (weight, size, style) => `${style ? style + " " : ""}${weight} ${size}px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`;

  const bgGrad = ctx.createLinearGradient(0, 0, 0, H);
  bgGrad.addColorStop(0, "#eaf4ec");
  bgGrad.addColorStop(1, "#ffffff");
  ctx.fillStyle = bgGrad;
  ctx.fillRect(0, 0, W, H);

  drawShareLogo(ctx, 90, 115, 64);
  ctx.fillStyle = "#1c1b19";
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.font = font(700, 48);
  ctx.fillText("Hotelify", 170, 147);

  ctx.textAlign = "center";
  ctx.textBaseline = "alphabetic";
  ctx.font = font(600, 40);
  ctx.fillStyle = "#7a756c";
  ctx.fillText("🏅 Achievement Unlocked", W / 2, 560);

  ctx.font = font(400, 260);
  ctx.fillText(badge.emoji, W / 2, 820);

  ctx.fillStyle = "#1c1b19";
  ctx.font = font(700, 72);
  wrapCenteredText(ctx, badge.label, W / 2, 940, 880, 84, 2);

  ctx.font = font(400, 40);
  ctx.fillStyle = "#7a756c";
  wrapCenteredText(ctx, badge.description, W / 2, 1060, 760, 54, 3);

  ctx.strokeStyle = "#e7e2da";
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(90, H - 160);
  ctx.lineTo(W - 90, H - 160);
  ctx.stroke();

  ctx.fillStyle = "#7a756c";
  ctx.font = font(500, 34);
  ctx.fillText("Earn your own badges at Hotelify", W / 2, H - 90);

  return canvas;
}

function openBadgeShareModal(badge) {
  const canvas = buildBadgeCanvas(badge);
  openCanvasShareModal(canvas, {
    altText: `${badge.label} badge`,
    filename: `hotelify-badge-${badge.id}.png`,
    shareText: `I just earned the "${badge.label}" badge on Hotelify! ${badge.emoji}`,
  });
}

function openCanvasShareModal(canvas, { altText, filename, shareText }) {
  const dataUrl = canvas.toDataURL("image/png");
  const canShareNative = typeof navigator.share === "function";

  const overlay = document.createElement("div");
  overlay.className = "share-modal-overlay";
  overlay.innerHTML = `
    <div class="share-modal">
      <button class="icon-btn share-modal-close" id="share-modal-close">✕ Close</button>
      <div class="share-canvas-wrap"><img src="${dataUrl}" alt="${escapeHtml(altText)}" /></div>
      <div class="share-modal-actions">
        <button class="pill-btn" id="share-download-btn">⬇️ Download</button>
        ${canShareNative ? `<button class="pill-btn ghost" id="share-native-btn">📤 Share</button>` : ""}
      </div>
      <p class="rank-sub share-modal-note">Long-press or right-click the image to save it, or use the buttons above — great for Instagram Stories or TikTok.</p>
    </div>
  `;
  document.body.appendChild(overlay);

  const close = () => overlay.remove();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.getElementById("share-modal-close").addEventListener("click", close);

  document.getElementById("share-download-btn").addEventListener("click", () => {
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    }, "image/png");
  });

  if (canShareNative) {
    document.getElementById("share-native-btn").addEventListener("click", () => {
      canvas.toBlob(async (blob) => {
        if (!blob) return;
        try {
          const file = new File([blob], filename, { type: "image/png" });
          if (navigator.canShare && !navigator.canShare({ files: [file] })) return;
          await navigator.share({ files: [file], title: "Hotelify", text: shareText });
        } catch (e) {
          // Share sheet dismissed or unsupported — nothing to do.
        }
      }, "image/png");
    });
  }
}


function renderBadgesSection() {
  const badges = computeEarnedBadges(state.journal);
  const tiles = badges
    .map(
      (b) => `
      <button class="badge-tile ${b.earned ? "badge-earned" : "badge-locked"}" ${b.earned ? `data-share-badge="${b.id}"` : "disabled"} title="${escapeHtml(b.description)}">
        <div class="badge-tile-emoji">${b.earned ? b.emoji : "🔒"}</div>
        <div class="badge-tile-label">${escapeHtml(b.label)}</div>
      </button>`
    )
    .join("");
  return `
    <div class="badges-section">
      <div class="detail-label">🏅 Badges</div>
      <div class="badge-grid">${tiles}</div>
    </div>`;
}

function renderJournal() {
  const badgesSection = renderBadgesSection();
  if (state.journal.length === 0) {
    return `
      <button class="icon-btn back-btn" data-step="city">← Back</button>
      <h2 class="step-heading">Your Trip Journal</h2>
      ${badgesSection}
      <div class="empty">No trips planned yet. Match your first hotel to start your journal.</div>
    `;
  }
  const rows = state.journal
    .map((j) => {
      const theme = THEME_META[j.themeKey];
      const color = j.score >= 75 ? "#2e7d4f" : j.score >= 50 ? "#b8860b" : "#c0392b";
      return `
      <li class="rank-row">
        <div class="rank-info">
          <div class="rank-name">${theme.emoji} ${escapeHtml(j.hotelName)}</div>
          <div class="rank-sub">${escapeHtml(j.city)} · ${theme.label} · ${timeAgo(j.timestamp)}</div>
        </div>
        <span class="badge" style="background:${color}">${j.score}%</span>
      </li>`;
    })
    .join("");

  return `
    <button class="icon-btn back-btn" data-step="city">← Back</button>
    <h2 class="step-heading">Your Trip Journal</h2>
    ${badgesSection}
    <ul class="rank-list">${rows}</ul>
  `;
}

// ---------- events ----------

function bindEvents() {
  const journalBtn = root.querySelector("[data-view-journal]");
  if (journalBtn) {
    journalBtn.addEventListener("click", () => {
      step = "journal";
      render();
    });
  }

  root.querySelectorAll("[data-step]").forEach((btn) => {
    btn.addEventListener("click", () => {
      step = btn.dataset.step;
      sharePlanError = null;
      sharePlanSuccess = false;
      planCheckError = null;
      render();
    });
  });

  const communityBtn = document.getElementById("view-community-btn");
  if (communityBtn) communityBtn.addEventListener("click", viewCommunity);

  const planCheckNotesInput = document.getElementById("plan-check-notes");
  if (planCheckNotesInput) {
    planCheckNotesInput.addEventListener("input", (e) => {
      planCheckNotes = e.target.value;
    });
  }

  const sharePlanBtn = document.getElementById("share-plan-btn");
  if (sharePlanBtn) sharePlanBtn.addEventListener("click", shareMyPlan);

  const signInBtn = document.getElementById("sign-in-btn");
  if (signInBtn) signInBtn.addEventListener("click", () => openAuthModal("signin"));

  const signOutBtn = document.getElementById("sign-out-btn");
  if (signOutBtn) {
    signOutBtn.addEventListener("click", async () => {
      await signOut();
    });
  }

  root.querySelectorAll("[data-share-badge]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const badge = BADGE_DEFS.find((b) => b.id === btn.dataset.shareBadge);
      if (badge) openBadgeShareModal(badge);
    });
  });

  const planNewBtn = root.querySelector("[data-plan-new]");
  if (planNewBtn) planNewBtn.addEventListener("click", planNewTrip);

  root.querySelectorAll(".change-key-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      clearGeminiKey();
      openApiKeyModal(() => render());
    });
  });

  const checkPlanBtn = document.getElementById("check-plan-btn");
  if (checkPlanBtn) checkPlanBtn.addEventListener("click", checkMyPlan);

  const addDayBtn = document.getElementById("add-day-btn");
  if (addDayBtn) addDayBtn.addEventListener("click", addPlanCheckDay);

  root.querySelectorAll("[data-remove-day]").forEach((btn) => {
    btn.addEventListener("click", () => removePlanCheckDay(Number(btn.dataset.removeDay)));
  });

  root.querySelectorAll("[data-add-stop-form]").forEach((form) => {
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const dayIndex = Number(form.dataset.addStopForm);
      const input = form.querySelector("input");
      addPlanCheckStop(dayIndex, input.value);
    });
  });

  root.querySelectorAll("[data-remove-stop]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const [dayIndex, stopIndex] = btn.dataset.removeStop.split("-").map(Number);
      removePlanCheckStop(dayIndex, stopIndex);
    });
  });

  root.querySelectorAll("[data-pick-city]").forEach((btn) => {
    btn.addEventListener("click", () => chooseCity(btn.dataset.pickCity));
  });

  root.querySelectorAll("[data-pick-hotel]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const hotel = MOCK_HOTELS.find((h) => h.id === btn.dataset.pickHotel);
      if (hotel) chooseHotel(hotel);
    });
  });

  root.querySelectorAll("[data-pick-theme]").forEach((btn) => {
    btn.addEventListener("click", () => chooseTheme(btn.dataset.pickTheme));
  });

  const cityInput = document.getElementById("city-input");
  if (cityInput) {
    cityInput.addEventListener("input", (e) => {
      cityQuery = e.target.value;
      const pos = e.target.selectionStart;
      render();
      const newInput = document.getElementById("city-input");
      if (newInput) {
        newInput.focus();
        newInput.setSelectionRange(pos, pos);
      }
    });
  }

  const showCustomBtn = document.getElementById("show-custom-hotel");
  if (showCustomBtn) {
    showCustomBtn.addEventListener("click", () => {
      showCustomHotelForm = true;
      render();
    });
  }

  const customForm = document.getElementById("custom-hotel-form");
  if (customForm) {
    customForm.addEventListener("submit", (e) => {
      e.preventDefault();
      const name = document.getElementById("custom-hotel-name").value.trim();
      if (!name) return;
      chooseHotel({ id: makeCustomId(), name, city: selectedCity, tags: [] });
    });
  }
}

render();
initAuth();
