// Mock hotel catalog used for search/autocomplete when adding a hotel.
// Users can also add a hotel not in this list via free text.
// `tier` (budget/moderate/luxury) and `tags` (nearby attractions) power
// the Discover tab's recommendation engine. `website` links to each
// hotel's real official site; `address` is best-effort and may be
// approximate for the smaller chain properties (h25+) — this is demo
// data, not a verified listings database.
const MOCK_HOTELS = [
  { id: "h1", name: "The Ritz-Carlton", city: "New York", country: "USA", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "50 Central Park South, New York, NY 10019", website: "https://www.ritzcarlton.com/en/hotels/nyc-new-york-central-park" , nearby: ["Central Park", "Carnegie Hall", "Fifth Avenue"] },
  { id: "h2", name: "Aman Tokyo", city: "Tokyo", country: "Japan", tier: "luxury", tags: ["Shopping", "Foodie"], address: "1-5-6 Otemachi, Chiyoda City, Tokyo 100-0004, Japan", website: "https://www.aman.com/hotels/aman-tokyo" , nearby: ["Imperial Palace", "Tokyo Station", "Marunouchi shopping district"] },
  { id: "h3", name: "Hotel Bel-Air", city: "Los Angeles", country: "USA", tier: "luxury", tags: ["Nature"], address: "701 Stone Canyon Rd, Los Angeles, CA 90077", website: "https://www.dorchestercollection.com/los-angeles/hotel-bel-air/" , nearby: ["Getty Center", "Rodeo Drive", "UCLA"] },
  { id: "h4", name: "Claridge's", city: "London", country: "UK", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Brook St, London W1K 4HR, UK", website: "https://www.claridges.co.uk/" , nearby: ["Bond Street", "Hyde Park", "Grosvenor Square"] },
  { id: "h5", name: "The Peninsula", city: "Hong Kong", country: "China", tier: "luxury", tags: ["Shopping", "Foodie"], address: "Salisbury Rd, Tsim Sha Tsui, Hong Kong", website: "https://www.peninsula.com/en/hong-kong/5-star-luxury-hotel-tsim-sha-tsui" , nearby: ["Victoria Harbour waterfront", "Avenue of Stars", "Hong Kong Museum of Art"] },
  { id: "h6", name: "Four Seasons George V", city: "Paris", country: "France", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "31 Avenue George V, 75008 Paris, France", website: "https://www.fourseasons.com/paris/" , nearby: ["Champs-Élysées", "Arc de Triomphe", "Eiffel Tower"] },
  { id: "h7", name: "Marina Bay Sands", city: "Singapore", country: "Singapore", tier: "luxury", tags: ["Shopping", "Nightlife"], address: "10 Bayfront Ave, Singapore 018956", website: "https://www.marinabaysands.com/" , nearby: ["Gardens by the Bay", "Merlion Park", "ArtScience Museum"] },
  { id: "h8", name: "The Plaza", city: "New York", country: "USA", tier: "luxury", tags: ["Historical", "Shopping"], address: "768 5th Ave, New York, NY 10019", website: "https://www.theplazany.com/" , nearby: ["Central Park", "Fifth Avenue", "Carnegie Hall"] },
  { id: "h9", name: "Burj Al Arab", city: "Dubai", country: "UAE", tier: "luxury", tags: ["Shopping", "Nightlife"], address: "Jumeirah St, Dubai, UAE", website: "https://www.jumeirah.com/en/stay/dubai/burj-al-arab" , nearby: ["Jumeirah Beach", "Wild Wadi Waterpark", "Madinat Jumeirah"] },
  { id: "h10", name: "Hotel de Russie", city: "Rome", country: "Italy", tier: "luxury", tags: ["Historical", "Museums"], address: "Via del Babuino, 9, 00187 Roma RM, Italy", website: "https://www.roccofortehotels.com/hotels-and-resorts/hotel-de-russie/" , nearby: ["Spanish Steps", "Piazza del Popolo", "Villa Borghese"] },
  { id: "h11", name: "The Beverly Hills Hotel", city: "Los Angeles", country: "USA", tier: "luxury", tags: ["Nightlife", "Shopping"], address: "9641 Sunset Blvd, Beverly Hills, CA 90210", website: "https://www.dorchestercollection.com/los-angeles/the-beverly-hills-hotel/" , nearby: ["Rodeo Drive", "Sunset Strip", "Beverly Gardens Park"] },
  { id: "h12", name: "Raffles", city: "Singapore", country: "Singapore", tier: "luxury", tags: ["Historical", "Shopping"], address: "1 Beach Rd, Singapore 189673", website: "https://www.raffles.com/singapore/" , nearby: ["Marina Bay", "Esplanade Theatres", "Merlion Park"] },
  { id: "h13", name: "The Gritti Palace", city: "Venice", country: "Italy", tier: "luxury", tags: ["Historical", "Museums"], address: "Campo Santa Maria del Giglio, 2467, 30124 Venezia VE, Italy", website: "https://www.thegrittipalace.com/" , nearby: ["St. Mark's Square", "Grand Canal", "Accademia Gallery"] },
  { id: "h14", name: "Post Ranch Inn", city: "Big Sur", country: "USA", tier: "luxury", tags: ["Nature"], address: "47900 CA-1, Big Sur, CA 93920", website: "https://www.postranchinn.com/" , nearby: ["Bixby Creek Bridge", "Pfeiffer Beach", "McWay Falls"] },
  { id: "h15", name: "Amangiri", city: "Canyon Point", country: "USA", tier: "luxury", tags: ["Nature"], address: "1 Kayenta Rd, Canyon Point, UT 84741", website: "https://www.aman.com/hotels/amangiri" , nearby: ["Lake Powell", "Antelope Canyon", "Grand Staircase-Escalante"] },
  { id: "h16", name: "The Connaught", city: "London", country: "UK", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Carlos Pl, London W1K 2AL, UK", website: "https://www.the-connaught.co.uk/" , nearby: ["Bond Street", "Grosvenor Square", "Hyde Park"] },
  { id: "h17", name: "Hotel Arts", city: "Barcelona", country: "Spain", tier: "luxury", tags: ["Beach", "Foodie"], address: "Carrer de la Marina, 19-21, 08005 Barcelona, Spain", website: "https://www.hotelartsbarcelona.com/" , nearby: ["Barceloneta Beach", "Port Olímpic", "Gothic Quarter"] },
  { id: "h18", name: "Park Hyatt", city: "Tokyo", country: "Japan", tier: "luxury", tags: ["Shopping", "Foodie"], address: "3-7-1-2 Nishishinjuku, Shinjuku City, Tokyo 163-1055, Japan", website: "https://www.hyatt.com/park-hyatt/en-US/tyoph-park-hyatt-tokyo" , nearby: ["Shinjuku Gyoen", "Tokyo Metropolitan Government Building", "Golden Gai"] },
  { id: "h19", name: "The Ned", city: "London", country: "UK", tier: "moderate", tags: ["Historical", "Nightlife", "Foodie"], address: "27 Poultry, London EC2R 8AJ, UK", website: "https://www.thened.com/" , nearby: ["Bank of England", "St. Paul's Cathedral", "Leadenhall Market"] },
  { id: "h20", name: "Rosewood Mayakoba", city: "Playa del Carmen", country: "Mexico", tier: "luxury", tags: ["Beach", "Nature"], address: "Carretera Federal Cancún-Playa del Carmen Km 298, 77710 Playa del Carmen, Mexico", website: "https://www.rosewoodhotels.com/en/mayakoba" , nearby: ["Playa del Carmen beach", "Xcaret Park", "5th Avenue Playa del Carmen"] },
  { id: "h21", name: "Nihi Sumba", city: "Sumba", country: "Indonesia", tier: "luxury", tags: ["Beach", "Nature"], address: "Desa Hobawawi, Wewewa Barat, Sumba Barat Daya, Indonesia", website: "https://www.nihi.com/" , nearby: ["Nihiwatu Beach", "Weekuri Lake", "Sumba traditional villages"] },
  { id: "h22", name: "The St. Regis", city: "New York", country: "USA", tier: "luxury", tags: ["Historical", "Shopping"], address: "2 E 55th St, New York, NY 10022", website: "https://www.marriott.com/en-us/hotels/nycsr-the-st-regis-new-york/" , nearby: ["Fifth Avenue", "MoMA", "Central Park"] },
  { id: "h23", name: "Belmond Hotel Caruso", city: "Ravello", country: "Italy", tier: "luxury", tags: ["Historical", "Beach"], address: "Piazza San Giovanni del Toro, 2, 84010 Ravello SA, Italy", website: "https://www.belmond.com/hotels/europe/italy/ravello/belmond-hotel-caruso/" , nearby: ["Villa Rufolo", "Ravello Cathedral", "Amalfi Coast viewpoints"] },
  { id: "h24", name: "Soho House", city: "Chicago", country: "USA", tier: "moderate", tags: ["Nightlife", "Foodie"], address: "113-125 N Green St, Chicago, IL 60607", website: "https://www.sohohouse.com/houses/soho-house-chicago" , nearby: ["West Loop restaurants", "Union Station", "Willis Tower"] },
  { id: "h25", name: "Pod Times Square", city: "New York", country: "USA", tier: "budget", tags: ["Nightlife", "Shopping"], address: "400 W 42nd St, New York, NY 10036", website: "https://www.thepodhotel.com/pod-times-square/" , nearby: ["Times Square", "Broadway theaters", "Bryant Park"] },
  { id: "h26", name: "citizenM Boston North Station", city: "Boston", country: "USA", tier: "moderate", tags: ["Historical"], address: "50 Causeway St, Boston, MA 02114", website: "https://www.citizenm.com/destinations/boston/boston-north-station-hotel" , nearby: ["TD Garden", "Faneuil Hall", "Freedom Trail"] },
  { id: "h27", name: "The Freehand", city: "Chicago", country: "USA", tier: "budget", tags: ["Nightlife", "Foodie"], address: "19 E Ohio St, Chicago, IL 60611", website: "https://www.freehandhotels.com/chicago/" , nearby: ["Magnificent Mile", "Navy Pier", "Millennium Park"] },
  { id: "h28", name: "Hotel Erwin", city: "Los Angeles", country: "USA", tier: "moderate", tags: ["Beach", "Nightlife"], address: "1697 Pacific Ave, Venice, CA 90291", website: "https://www.hotelerwin.com/" , nearby: ["Venice Beach Boardwalk", "Muscle Beach", "Abbot Kinney Blvd"] },
  { id: "h29", name: "Yotel San Francisco", city: "San Francisco", country: "USA", tier: "budget", tags: ["Foodie"], address: "1095 Market St, San Francisco, CA 94103", website: "https://www.yotel.com/en/hotels/yotel-san-francisco" , nearby: ["Union Square", "Moscone Center", "SFMOMA"] },
  { id: "h30", name: "The Loren at Lady Bird Lake", city: "Austin", country: "USA", tier: "moderate", tags: ["Nature", "Nightlife"], address: "1211 S 1st St, Austin, TX 78704", website: "https://www.thelorenhotel.com/" , nearby: ["Lady Bird Lake Trail", "Rainey Street District", "Texas State Capitol"] },
  { id: "h31", name: "Generator Miami", city: "Miami", country: "USA", tier: "budget", tags: ["Beach", "Nightlife"], address: "2340 Collins Ave, Miami Beach, FL 33139", website: "https://staygenerator.com/hostels/miami" , nearby: ["South Beach", "Art Deco Historic District", "Lincoln Road"] },
  { id: "h32", name: "Found Hotel Chicago", city: "Chicago", country: "USA", tier: "budget", tags: ["Historical"], address: "Downtown Chicago, IL", website: "https://www.foundhotels.com/" , nearby: ["Millennium Park", "The Loop", "Art Institute of Chicago"] },

  // More options for cities that only had one hotel on file
  { id: "h33", name: "Rosewood Hong Kong", city: "Hong Kong", country: "China", tier: "luxury", tags: ["Shopping", "Foodie", "Nightlife"], address: "18 Salisbury Rd, Tsim Sha Tsui, Hong Kong", website: "https://www.rosewoodhotels.com/en/hong-kong" , nearby: ["Victoria Harbour", "Avenue of Stars", "K11 MUSEA"] },
  { id: "h34", name: "Hotel Eden", city: "Rome", country: "Italy", tier: "luxury", tags: ["Historical", "Museums", "Foodie"], address: "Via Ludovisi, 49, 00187 Roma RM, Italy", website: "https://www.dorchestercollection.com/rome/hotel-eden/" , nearby: ["Villa Borghese", "Spanish Steps", "Via Veneto"] },
  { id: "h35", name: "Hotel Danieli", city: "Venice", country: "Italy", tier: "luxury", tags: ["Historical", "Museums"], address: "Riva degli Schiavoni, 4196, 30122 Venezia VE, Italy", website: "https://www.marriott.com/en-us/hotels/vcedi-hotel-danieli-a-luxury-collection-hotel-venice/" , nearby: ["St. Mark's Square", "Bridge of Sighs", "Doge's Palace"] },
  { id: "h36", name: "Ventana Big Sur", city: "Big Sur", country: "USA", tier: "luxury", tags: ["Nature"], address: "48123 CA-1, Big Sur, CA 93920", website: "https://www.ventanabigsur.com/" , nearby: ["Point Sur Lighthouse", "Pfeiffer Big Sur State Park", "Big Sur River"] },
  { id: "h37", name: "W Barcelona", city: "Barcelona", country: "Spain", tier: "luxury", tags: ["Beach", "Nightlife"], address: "Plaça Rosa dels Vents, 1, 08039 Barcelona, Spain", website: "https://www.marriott.com/en-us/hotels/bcnwh-w-barcelona/" , nearby: ["Barceloneta Beach", "Port Vell", "La Barceloneta neighborhood"] },
  { id: "h38", name: "Mahekal Beach Resort", city: "Playa del Carmen", country: "Mexico", tier: "moderate", tags: ["Beach", "Nature"], address: "Calle 38 Norte, Playa del Carmen, Mexico", website: "https://www.mahekalbeachresort.com/" , nearby: ["Playa del Carmen 5th Avenue", "Mamitas Beach", "Cozumel ferry pier"] },
  { id: "h39", name: "Palazzo Avino", city: "Ravello", country: "Italy", tier: "luxury", tags: ["Historical", "Beach"], address: "Via San Giovanni del Toro, 28, 84010 Ravello SA, Italy", website: "https://www.palazzoavino.com/" , nearby: ["Villa Cimbrone", "Ravello Cathedral", "Amalfi Coast"] },
  { id: "h40", name: "The Liberty Hotel", city: "Boston", country: "USA", tier: "luxury", tags: ["Historical", "Nightlife"], address: "215 Charles St, Boston, MA 02114", website: "https://www.libertyhotel.com/" , nearby: ["Beacon Hill", "Charles River Esplanade", "Massachusetts General Hospital area"] },
  { id: "h41", name: "Fairmont San Francisco", city: "San Francisco", country: "USA", tier: "luxury", tags: ["Historical", "Shopping"], address: "950 Mason St, San Francisco, CA 94108", website: "https://www.fairmont.com/san-francisco/" , nearby: ["Grace Cathedral", "Lombard Street", "Union Square"] },
  { id: "h42", name: "Hotel Van Zandt", city: "Austin", country: "USA", tier: "moderate", tags: ["Nightlife", "Foodie"], address: "605 Davis St, Austin, TX 78701", website: "https://www.hotelvanzandt.com/" , nearby: ["Rainey Street District", "Lady Bird Lake", "Downtown Austin"] },
  { id: "h43", name: "Fontainebleau Miami Beach", city: "Miami", country: "USA", tier: "luxury", tags: ["Beach", "Nightlife"], address: "4441 Collins Ave, Miami Beach, FL 33140", website: "https://www.fontainebleau.com/" , nearby: ["Mid-Beach", "Collins Avenue", "Faena District"] },
  { id: "h44", name: "Atlantis The Palm", city: "Dubai", country: "UAE", tier: "luxury", tags: ["Beach", "Nightlife"], address: "Crescent Rd, Dubai, UAE", website: "https://www.atlantis.com/dubai" , nearby: ["Palm Jumeirah", "Aquaventure Waterpark", "The Pointe"] },
  { id: "h45", name: "The Fullerton Hotel Singapore", city: "Singapore", country: "Singapore", tier: "luxury", tags: ["Historical", "Shopping"], address: "1 Fullerton Square, Singapore 049178", website: "https://www.fullertonhotels.com/fullerton-hotel-singapore" , nearby: ["Marina Bay", "Merlion Park", "Boat Quay"] },
  { id: "h46", name: "Hotel Boss", city: "Singapore", country: "Singapore", tier: "budget", tags: ["Shopping", "Foodie"], address: "500 Jln Sultan, Singapore", website: "https://www.hotelboss.com.sg/" , nearby: ["Bugis Street Market", "Kampong Glam", "Sultan Mosque"] },
  { id: "h47", name: "Shibuya Granbell Hotel", city: "Tokyo", country: "Japan", tier: "budget", tags: ["Nightlife", "Shopping", "Foodie"], address: "15-17 Sakuragaokacho, Shibuya City, Tokyo, Japan", website: "https://www.granbellhotel.jp/shibuya/" , nearby: ["Shibuya Crossing", "Shibuya Scramble Square", "Meiji Shrine"] },

  // New cities
  { id: "h48", name: "Waldorf Astoria Amsterdam", city: "Amsterdam", country: "Netherlands", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Herengracht 542-556, 1017 CG Amsterdam, Netherlands", website: "https://www.hilton.com/en/hotels/amswawa-waldorf-astoria-amsterdam/" , nearby: ["Herengracht canal", "Anne Frank House", "Dam Square"] },
  { id: "h49", name: "Generator Amsterdam", city: "Amsterdam", country: "Netherlands", tier: "budget", tags: ["Nightlife", "Foodie"], address: "Mauritskade 57, 1092 AD Amsterdam, Netherlands", website: "https://staygenerator.com/hostels/amsterdam" , nearby: ["Oosterpark", "Tropenmuseum", "Artis Zoo"] },
  { id: "h50", name: "Hotel Adlon Kempinski", city: "Berlin", country: "Germany", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Unter den Linden 77, 10117 Berlin, Germany", website: "https://www.kempinski.com/en/hotel-adlon" , nearby: ["Brandenburg Gate", "Museum Island", "Pariser Platz"] },
  { id: "h51", name: "25hours Hotel Bikini Berlin", city: "Berlin", country: "Germany", tier: "moderate", tags: ["Shopping", "Nightlife", "Foodie"], address: "Budapester Str. 40, 10787 Berlin, Germany", website: "https://www.25hours-hotels.com/en/hotels/berlin/bikini-berlin" , nearby: ["Berlin Zoo", "Kurfürstendamm", "Kaiser Wilhelm Memorial Church"] },
  { id: "h52", name: "Mandarin Oriental Bangkok", city: "Bangkok", country: "Thailand", tier: "luxury", tags: ["Historical", "Foodie", "Nightlife"], address: "48 Oriental Ave, Bangkok, Thailand", website: "https://www.mandarinoriental.com/bangkok" , nearby: ["Chao Phraya River", "Wat Arun", "Asiatique The Riverfront"] },
  { id: "h53", name: "Lub d Bangkok Silom", city: "Bangkok", country: "Thailand", tier: "budget", tags: ["Nightlife", "Foodie"], address: "4 Decho Rd, Bangkok, Thailand", website: "https://www.lubd.com/" , nearby: ["Patpong Night Market", "Lumpini Park", "Sala Daeng BTS station"] },
  { id: "h54", name: "Park Hyatt Sydney", city: "Sydney", country: "Australia", tier: "luxury", tags: ["Historical", "Beach", "Foodie"], address: "7 Hickson Rd, The Rocks NSW 2000, Australia", website: "https://www.hyatt.com/park-hyatt/en-US/sydph-park-hyatt-sydney" , nearby: ["Sydney Opera House", "Harbour Bridge", "The Rocks Markets"] },
  { id: "h55", name: "Sydney Harbour YHA", city: "Sydney", country: "Australia", tier: "budget", tags: ["Historical", "Beach"], address: "110 Cumberland St, The Rocks NSW 2000, Australia", website: "https://www.yha.com.au/hostels/nsw/sydney-surrounds/sydney-harbour-yha/" , nearby: ["The Rocks", "Circular Quay", "Sydney Observatory Hill"] },
  { id: "h56", name: "Four Seasons Hotel Ritz Lisbon", city: "Lisbon", country: "Portugal", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Rua Rodrigo da Fonseca 88, 1099-039 Lisboa, Portugal", website: "https://www.fourseasons.com/lisbon/" , nearby: ["Eduardo VII Park", "Gulbenkian Museum", "Avenida da Liberdade"] },
  { id: "h57", name: "Home Lisbon Hostel", city: "Lisbon", country: "Portugal", tier: "budget", tags: ["Historical", "Nightlife", "Foodie"], address: "Rua São Nicolau 13, Lisbon, Portugal", website: "https://www.homelisbonhostel.com/" , nearby: ["Rossio Square", "Santa Justa Lift", "Alfama district"] },
  { id: "h58", name: "Four Seasons Hotel Mexico City", city: "Mexico City", country: "Mexico", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Paseo de la Reforma 500, Mexico City, Mexico", website: "https://www.fourseasons.com/mexico/" , nearby: ["Chapultepec Park", "Angel of Independence", "Zona Rosa"] },
  { id: "h59", name: "Mundo Joven Catedral", city: "Mexico City", country: "Mexico", tier: "budget", tags: ["Historical", "Nightlife"], address: "República de Guatemala 4, Mexico City, Mexico", website: "https://www.mundojovenhostels.com/" , nearby: ["Zócalo", "Metropolitan Cathedral", "Templo Mayor"] },
  { id: "h60", name: "Bellagio Las Vegas", city: "Las Vegas", country: "USA", tier: "luxury", tags: ["Nightlife", "Shopping", "Foodie"], address: "3600 S Las Vegas Blvd, Las Vegas, NV 89109", website: "https://bellagio.mgmresorts.com/" , nearby: ["Bellagio Fountains", "The Strip", "Caesars Palace"] },
  { id: "h61", name: "The LINQ Hotel", city: "Las Vegas", country: "USA", tier: "moderate", tags: ["Nightlife", "Shopping"], address: "3535 S Las Vegas Blvd, Las Vegas, NV 89109", website: "https://www.caesars.com/linq" , nearby: ["High Roller Observation Wheel", "LINQ Promenade", "Flamingo Las Vegas"] },
  { id: "h62", name: "Four Seasons Hotel Seattle", city: "Seattle", country: "USA", tier: "luxury", tags: ["Historical", "Shopping", "Foodie"], address: "99 Union St, Seattle, WA 98101", website: "https://www.fourseasons.com/seattle/" , nearby: ["Pike Place Market", "Seattle Art Museum", "Puget Sound waterfront"] },
  { id: "h63", name: "Green Tortoise Hostel Seattle", city: "Seattle", country: "USA", tier: "budget", tags: ["Historical", "Nightlife"], address: "105 Pike St, Seattle, WA 98101", website: "https://www.greentortoise.net/seattle" , nearby: ["Pike Place Market", "Seattle Waterfront", "Pioneer Square"] },

  // More new cities
  { id: "h64", name: "Hotel Sacher Wien", city: "Vienna", country: "Austria", tier: "luxury", tags: ["Historical", "Museums", "Foodie"], address: "Philharmoniker Str. 4, 1010 Wien, Austria", website: "https://www.sacher.com/en/hotel-sacher-wien/", nearby: ["Vienna State Opera", "Albertina Museum", "Stephansplatz"] },
  { id: "h65", name: "Four Seasons Hotel Istanbul at Sultanahmet", city: "Istanbul", country: "Turkey", tier: "luxury", tags: ["Historical", "Museums"], address: "Tevkifhane Sok. No:1, Sultanahmet, Istanbul, Turkey", website: "https://www.fourseasons.com/istanbul/", nearby: ["Hagia Sophia", "Blue Mosque", "Topkapi Palace"] },
  { id: "h66", name: "The Augustine, a Luxury Collection Hotel", city: "Prague", country: "Czech Republic", tier: "luxury", tags: ["Historical", "Nightlife"], address: "Letenská 12/33, 118 00 Praha, Czech Republic", website: "https://www.marriott.com/en-us/hotels/prgak-the-augustine-a-luxury-collection-hotel-prague/", nearby: ["Prague Castle", "Charles Bridge", "Lesser Town Square"] },
  { id: "h67", name: "The Shelbourne", city: "Dublin", country: "Ireland", tier: "luxury", tags: ["Historical", "Shopping", "Nightlife"], address: "27 St Stephen's Green, Dublin 2, Ireland", website: "https://www.marriott.com/en-us/hotels/dubbr-the-shelbourne-autograph-collection/", nearby: ["St Stephen's Green", "Grafton Street", "Trinity College"] },
  { id: "h68", name: "Hotel d'Angleterre", city: "Copenhagen", country: "Denmark", tier: "luxury", tags: ["Historical", "Foodie"], address: "Kongens Nytorv 34, 1050 København, Denmark", website: "https://www.dangleterre.com/", nearby: ["Nyhavn", "Kongens Nytorv", "Tivoli Gardens"] },
  { id: "h69", name: "Belmond Copacabana Palace", city: "Rio de Janeiro", country: "Brazil", tier: "luxury", tags: ["Beach", "Nightlife"], address: "Av. Atlântica, 1702, Copacabana, Rio de Janeiro, Brazil", website: "https://www.belmond.com/hotels/south-america/brazil/rio-de-janeiro/belmond-copacabana-palace/", nearby: ["Copacabana Beach", "Sugarloaf Mountain", "Ipanema"] },
  { id: "h70", name: "The Silo Hotel", city: "Cape Town", country: "South Africa", tier: "luxury", tags: ["Museums", "Beach", "Foodie"], address: "Silo Square, V&A Waterfront, Cape Town, South Africa", website: "https://www.theroyalportfolio.com/the-silo/", nearby: ["Zeitz MOCAA", "V&A Waterfront", "Table Mountain"] },
  { id: "h71", name: "La Mamounia", city: "Marrakech", country: "Morocco", tier: "luxury", tags: ["Historical", "Nightlife"], address: "Avenue Bab Jdid, Marrakech, Morocco", website: "https://www.mamounia.com/", nearby: ["Jemaa el-Fnaa", "Koutoubia Mosque", "Majorelle Garden"] },
  { id: "h72", name: "The Ritz-Carlton Kyoto", city: "Kyoto", country: "Japan", tier: "luxury", tags: ["Historical", "Nature"], address: "Kamogawa Nijo-Ohashi Hotori, Nakagyo Ward, Kyoto, Japan", website: "https://www.ritzcarlton.com/en/hotels/japan/kyoto", nearby: ["Kamo River", "Nijo Castle", "Gion district"] },
  { id: "h73", name: "Hotel Monteleone", city: "New Orleans", country: "USA", tier: "moderate", tags: ["Historical", "Nightlife", "Foodie"], address: "214 Royal St, New Orleans, LA 70130", website: "https://www.hotelmonteleone.com/", nearby: ["French Quarter", "Bourbon Street", "Jackson Square"] },

  // Even more new cities
  { id: "h74", name: "The Ritz-Carlton Toronto", city: "Toronto", country: "Canada", tier: "luxury", tags: ["Shopping", "Nightlife", "Foodie"], address: "181 Wellington St W, Toronto, ON M5V 3G7, Canada", website: "https://www.ritzcarlton.com/en/hotels/toronto", nearby: ["CN Tower", "Rogers Centre", "Entertainment District"] },
  { id: "h75", name: "The Balmoral", city: "Edinburgh", country: "UK", tier: "luxury", tags: ["Historical", "Shopping"], address: "1 Princes St, Edinburgh EH2 2EQ, UK", website: "https://www.roccofortehotels.com/hotels-and-resorts/the-balmoral-hotel/", nearby: ["Edinburgh Castle", "Princes Street Gardens", "Royal Mile"] },
  { id: "h76", name: "Canaves Oia Suites", city: "Santorini", country: "Greece", tier: "luxury", tags: ["Beach", "Nature"], address: "Oia, 847 02, Santorini, Greece", website: "https://www.canaves.com/", nearby: ["Oia Castle", "Caldera viewpoints", "Ammoudi Bay"] },
  { id: "h77", name: "Alvear Palace Hotel", city: "Buenos Aires", country: "Argentina", tier: "luxury", tags: ["Historical", "Shopping"], address: "Av. Alvear 1891, C1129AAA CABA, Argentina", website: "https://www.alvearpalace.com/", nearby: ["Recoleta Cemetery", "Avenida Alvear", "Floralis Genérica"] },
  { id: "h78", name: "Four Seasons Hotel Seoul", city: "Seoul", country: "South Korea", tier: "luxury", tags: ["Historical", "Shopping", "Foodie"], address: "97 Saemunan-ro, Jongno-gu, Seoul, South Korea", website: "https://www.fourseasons.com/seoul/", nearby: ["Gyeongbokgung Palace", "Gwanghwamun Square", "Bukchon Hanok Village"] },
  { id: "h79", name: "Hotel Borg by Keahotels", city: "Reykjavik", country: "Iceland", tier: "moderate", tags: ["Historical", "Nature"], address: "Pósthússtræti 11, 101 Reykjavík, Iceland", website: "https://www.hotelborg.is/", nearby: ["Austurvöllur Square", "Harpa Concert Hall", "Reykjavik Cathedral"] },
  { id: "h80", name: "Four Seasons Resort Bali at Sayan", city: "Ubud", country: "Indonesia", tier: "luxury", tags: ["Nature", "Foodie"], address: "Sayan, Ubud, Gianyar, Bali, Indonesia", website: "https://www.fourseasons.com/sayan/", nearby: ["Sayan Ridge", "Ubud Monkey Forest", "Ubud Art Market"] },
  { id: "h81", name: "Fairmont Pacific Rim", city: "Vancouver", country: "Canada", tier: "luxury", tags: ["Nature", "Shopping", "Foodie"], address: "1038 Canada Pl, Vancouver, BC V6C 0B9, Canada", website: "https://www.fairmont.com/pacific-rim-vancouver/", nearby: ["Canada Place", "Stanley Park", "Coal Harbour"] },
  { id: "h82", name: "Baur au Lac", city: "Zurich", country: "Switzerland", tier: "luxury", tags: ["Shopping", "Historical"], address: "Talstrasse 1, 8001 Zürich, Switzerland", website: "https://www.bauraulac.ch/", nearby: ["Lake Zurich", "Bahnhofstrasse", "Zurich Opera House"] },
  { id: "h83", name: "Sofitel Legend Metropole Hanoi", city: "Hanoi", country: "Vietnam", tier: "luxury", tags: ["Historical", "Foodie"], address: "15 Ngo Quyen St, Hoan Kiem, Hanoi, Vietnam", website: "https://www.sofitel-legend-metropole-hanoi.com/", nearby: ["Hoan Kiem Lake", "Hanoi Opera House", "Old Quarter"] },

  // Round 3: more cities and more budget/moderate options
  { id: "h84", name: "Hôtel Plaza Athénée", city: "Paris", country: "France", tier: "luxury", tags: ["Shopping", "Foodie", "Historical"], address: "25 Avenue Montaigne, 75008 Paris, France", website: "https://www.dorchestercollection.com/paris/hotel-plaza-athenee/", nearby: ["Eiffel Tower", "Avenue Montaigne", "Champs-Élysées"] },
  { id: "h85", name: "Generator Paris", city: "Paris", country: "France", tier: "budget", tags: ["Nightlife", "Foodie"], address: "9-11 Place du Colonel Fabien, 75010 Paris, France", website: "https://staygenerator.com/hostels/paris", nearby: ["Canal Saint-Martin", "Montmartre", "Sacré-Cœur"] },
  { id: "h86", name: "The Savoy", city: "London", country: "UK", tier: "luxury", tags: ["Historical", "Museums", "Nightlife"], address: "Strand, London WC2R 0EZ, UK", website: "https://www.thesavoylondon.com/", nearby: ["Covent Garden", "Trafalgar Square", "River Thames"] },
  { id: "h87", name: "Premier Inn London County Hall", city: "London", country: "UK", tier: "budget", tags: ["Museums", "Historical"], address: "Belvedere Rd, London SE1 7PB, UK", website: "https://www.premierinn.com/", nearby: ["London Eye", "Big Ben", "Southbank"] },
  { id: "h88", name: "The Standard, High Line", city: "New York", country: "USA", tier: "moderate", tags: ["Nightlife", "Foodie"], address: "848 Washington St, New York, NY 10014", website: "https://www.standardhotels.com/new-york/properties/high-line", nearby: ["High Line", "Chelsea Market", "Whitney Museum"] },
  { id: "h89", name: "YOTEL New York", city: "New York", country: "USA", tier: "budget", tags: ["Nightlife", "Shopping"], address: "570 10th Ave, New York, NY 10036", website: "https://www.yotel.com/en/hotels/yotel-new-york", nearby: ["Hudson Yards", "Times Square", "Intrepid Museum"] },
  { id: "h90", name: "The Hoxton, Williamsburg", city: "New York", country: "USA", tier: "moderate", tags: ["Nightlife", "Foodie"], address: "97 Wythe Ave, Brooklyn, NY 11249", website: "https://thehoxton.com/williamsburg/", nearby: ["Domino Park", "Brooklyn Brewery", "Williamsburg waterfront"] },
  { id: "h91", name: "The Hay-Adams", city: "Washington", country: "USA", tier: "luxury", tags: ["Historical", "Museums"], address: "800 16th St NW, Washington, DC 20006", website: "https://www.hayadams.com/", nearby: ["White House", "Lafayette Square", "National Mall"] },
  { id: "h92", name: "Hotel Hive", city: "Washington", country: "USA", tier: "budget", tags: ["Museums", "Historical"], address: "2224 F St NW, Washington, DC 20037", website: "https://www.hotelhive.com/", nearby: ["Kennedy Center", "Lincoln Memorial", "George Washington University"] },
  { id: "h93", name: "Halekulani", city: "Honolulu", country: "USA", tier: "luxury", tags: ["Beach"], address: "2199 Kalia Rd, Honolulu, HI 96815", website: "https://www.halekulani.com/", nearby: ["Waikiki Beach", "Diamond Head", "Kalakaua Avenue"] },
  { id: "h94", name: "Moana Surfrider, A Westin Resort", city: "Honolulu", country: "USA", tier: "luxury", tags: ["Beach", "Historical", "Shopping"], address: "2365 Kalakaua Ave, Honolulu, HI 96815", website: "https://www.marriott.com/en-us/hotels/hnlms-moana-surfrider-a-westin-resort-and-spa/", nearby: ["Waikiki Beach", "Royal Hawaiian Center", "Kuhio Beach"] },
  { id: "h95", name: "Hotel del Coronado", city: "San Diego", country: "USA", tier: "luxury", tags: ["Beach", "Historical"], address: "1500 Orange Ave, Coronado, CA 92118", website: "https://www.hoteldel.com/", nearby: ["Coronado Beach", "Coronado Ferry Landing", "Balboa Park"] },
  { id: "h96", name: "The Hermitage Hotel", city: "Nashville", country: "USA", tier: "luxury", tags: ["Historical", "Nightlife", "Foodie"], address: "231 6th Ave N, Nashville, TN 37219", website: "https://www.thehermitagehotel.com/", nearby: ["Broadway honky-tonks", "Country Music Hall of Fame", "Tennessee State Capitol"] },
  { id: "h97", name: "The Mansion on Forsyth Park", city: "Savannah", country: "USA", tier: "luxury", tags: ["Historical", "Foodie"], address: "700 Drayton St, Savannah, GA 31401", website: "https://www.mansionforsythpark.com/", nearby: ["Forsyth Park", "Historic District", "River Street"] },
  { id: "h98", name: "The Roosevelt New Orleans", city: "New Orleans", country: "USA", tier: "luxury", tags: ["Historical", "Nightlife", "Foodie"], address: "130 Roosevelt Way, New Orleans, LA 70112", website: "https://www.rooseveltneworleans.com/", nearby: ["French Quarter", "Canal Street", "Louis Armstrong Park"] },
  { id: "h99", name: "The Betsy South Beach", city: "Miami", country: "USA", tier: "luxury", tags: ["Beach", "Historical", "Nightlife"], address: "1440 Ocean Dr, Miami Beach, FL 33139", website: "https://www.thebetsyhotel.com/", nearby: ["Ocean Drive", "Lummus Park Beach", "Art Deco Historic District"] },
  { id: "h100", name: "The Langham, Chicago", city: "Chicago", country: "USA", tier: "luxury", tags: ["Shopping", "Foodie", "Museums"], address: "330 N Wabash Ave, Chicago, IL 60611", website: "https://www.langhamhotels.com/en/the-langham/chicago/", nearby: ["Chicago Riverwalk", "Magnificent Mile", "Millennium Park"] },
  { id: "h101", name: "The Langham, Boston", city: "Boston", country: "USA", tier: "luxury", tags: ["Historical", "Foodie"], address: "250 Franklin St, Boston, MA 02110", website: "https://www.langhamhotels.com/en/the-langham/boston/", nearby: ["Faneuil Hall", "Boston Common", "Freedom Trail"] },
  { id: "h102", name: "Hotel Zephyr San Francisco", city: "San Francisco", country: "USA", tier: "moderate", tags: ["Foodie", "Historical"], address: "250 Beach St, San Francisco, CA 94133", website: "https://www.hotelzephyrsf.com/", nearby: ["Fisherman's Wharf", "Pier 39", "Alcatraz ferry"] },
  { id: "h103", name: "The Beehive Rome", city: "Rome", country: "Italy", tier: "budget", tags: ["Historical", "Foodie"], address: "Via Marghera 8, 00185 Roma RM, Italy", website: "https://www.the-beehive.com/", nearby: ["Termini Station", "Colosseum", "Santa Maria Maggiore"] },
  { id: "h104", name: "Generator Venice", city: "Venice", country: "Italy", tier: "budget", tags: ["Historical", "Museums"], address: "Fondamenta Zitelle 86, Giudecca, 30133 Venezia VE, Italy", website: "https://staygenerator.com/hostels/venice", nearby: ["Giudecca Canal", "Redentore Church", "St. Mark's Square"] },
  { id: "h105", name: "Casa Camper Barcelona", city: "Barcelona", country: "Spain", tier: "moderate", tags: ["Foodie", "Nightlife", "Museums"], address: "Carrer d'Elisabets 11, 08001 Barcelona, Spain", website: "https://www.casacamper.com/en/barcelona", nearby: ["MACBA", "La Rambla", "Gothic Quarter"] },
  { id: "h106", name: "Generator Barcelona", city: "Barcelona", country: "Spain", tier: "budget", tags: ["Nightlife", "Historical"], address: "Carrer de Còrsega 373, 08037 Barcelona, Spain", website: "https://staygenerator.com/hostels/barcelona", nearby: ["Sagrada Família", "Casa Batlló", "Passeig de Gràcia"] },
  { id: "h107", name: "Hotel Gracery Shinjuku", city: "Tokyo", country: "Japan", tier: "moderate", tags: ["Nightlife", "Foodie"], address: "1-19-1 Kabukicho, Shinjuku City, Tokyo 160-8466, Japan", website: "https://shinjuku.gracery.com/", nearby: ["Kabukicho", "Golden Gai", "Shinjuku Gyoen"] },
  { id: "h108", name: "Hotel Granvia Kyoto", city: "Kyoto", country: "Japan", tier: "moderate", tags: ["Historical", "Shopping"], address: "JR Kyoto Station, Karasuma Chuo-guchi, Shimogyo Ward, Kyoto, Japan", website: "https://www.granviakyoto.com/en/", nearby: ["Kyoto Tower", "Kyoto Station", "Toji Temple"] },
  { id: "h109", name: "The Siam", city: "Bangkok", country: "Thailand", tier: "luxury", tags: ["Historical", "Foodie"], address: "3/2 Khao Rd, Dusit, Bangkok 10300, Thailand", website: "https://www.thesiamhotel.com/", nearby: ["Chao Phraya River", "Wat Benchamabophit", "Dusit Palace"] },
  { id: "h110", name: "Capella Singapore", city: "Singapore", country: "Singapore", tier: "luxury", tags: ["Beach", "Nature"], address: "1 The Knolls, Sentosa Island, Singapore 098297", website: "https://www.capellahotels.com/en/capella-singapore", nearby: ["Sentosa beaches", "Universal Studios Singapore", "S.E.A. Aquarium"] },
  { id: "h111", name: "Rove Downtown", city: "Dubai", country: "UAE", tier: "moderate", tags: ["Shopping"], address: "Downtown Dubai, Dubai, UAE", website: "https://www.rovehotels.com/", nearby: ["Burj Khalifa", "Dubai Mall", "Dubai Fountain"] },
  { id: "h112", name: "The Langham, Sydney", city: "Sydney", country: "Australia", tier: "luxury", tags: ["Historical", "Foodie"], address: "89-113 Kent St, Millers Point NSW 2000, Australia", website: "https://www.langhamhotels.com/en/the-langham/sydney/", nearby: ["Sydney Harbour Bridge", "The Rocks", "Barangaroo"] },
  { id: "h113", name: "Hotel Lindrum Melbourne", city: "Melbourne", country: "Australia", tier: "luxury", tags: ["Foodie", "Shopping"], address: "26 Flinders St, Melbourne VIC 3000, Australia", website: "https://www.hotellindrum.com.au/", nearby: ["Federation Square", "Flinders Street Station", "Melbourne Cricket Ground"] },
  { id: "h114", name: "The Taj Mahal Palace", city: "Mumbai", country: "India", tier: "luxury", tags: ["Historical", "Foodie"], address: "Apollo Bandar, Colaba, Mumbai 400001, India", website: "https://www.tajhotels.com/en-in/taj/taj-mahal-palace-mumbai/", nearby: ["Gateway of India", "Colaba Causeway", "Marine Drive"] },
  { id: "h115", name: "The Imperial New Delhi", city: "Delhi", country: "India", tier: "luxury", tags: ["Historical", "Shopping"], address: "Janpath, Connaught Place, New Delhi 110001, India", website: "https://www.theimperialindia.com/", nearby: ["Connaught Place", "India Gate", "Jantar Mantar"] },
  { id: "h116", name: "Hotel Vier Jahreszeiten Kempinski", city: "Munich", country: "Germany", tier: "luxury", tags: ["Historical", "Shopping"], address: "Maximilianstraße 17, 80539 München, Germany", website: "https://www.kempinski.com/en/munich/hotel-vier-jahreszeiten/", nearby: ["Marienplatz", "Maximilianstrasse", "Munich Residenz"] },
  { id: "h117", name: "Four Seasons Hotel Gresham Palace", city: "Budapest", country: "Hungary", tier: "luxury", tags: ["Historical", "Foodie"], address: "Széchenyi István tér 5-6, 1051 Budapest, Hungary", website: "https://www.fourseasons.com/budapest/", nearby: ["Chain Bridge", "Danube Promenade", "Hungarian Parliament"] },
  { id: "h118", name: "Hotel Savoy Florence", city: "Florence", country: "Italy", tier: "luxury", tags: ["Historical", "Museums", "Shopping"], address: "Piazza della Repubblica 7, 50123 Firenze FI, Italy", website: "https://www.roccofortehotels.com/hotels-and-resorts/hotel-savoy/", nearby: ["Duomo", "Uffizi Gallery", "Ponte Vecchio"] },
  { id: "h119", name: "Hotel Grande Bretagne", city: "Athens", country: "Greece", tier: "luxury", tags: ["Historical", "Museums"], address: "Vasileos Georgiou A' 1, Syntagma Square, Athens 105 64, Greece", website: "https://www.marriott.com/en-us/hotels/athgb-hotel-grande-bretagne-a-luxury-collection-hotel-athens/", nearby: ["Acropolis", "Syntagma Square", "Plaka"] },
  { id: "h120", name: "Mandarin Oriental Ritz, Madrid", city: "Madrid", country: "Spain", tier: "luxury", tags: ["Museums", "Historical"], address: "Plaza de la Lealtad 5, 28014 Madrid, Spain", website: "https://www.mandarinoriental.com/en/madrid/ritz", nearby: ["Prado Museum", "Retiro Park", "Plaza de Cibeles"] },
  { id: "h121", name: "Generator Madrid", city: "Madrid", country: "Spain", tier: "budget", tags: ["Nightlife", "Foodie"], address: "Chueca district, Madrid, Spain", website: "https://staygenerator.com/hostels/madrid", nearby: ["Gran Vía", "Chueca", "Puerta del Sol"] },
  { id: "h122", name: "The Lumiares Hotel & Spa", city: "Lisbon", country: "Portugal", tier: "moderate", tags: ["Nightlife", "Foodie"], address: "Rua do Diário de Notícias 142, 1200-189 Lisboa, Portugal", website: "https://www.thelumiares.com/", nearby: ["Bairro Alto", "Miradouro de São Pedro de Alcântara", "Chiado"] },
  { id: "h123", name: "Hotel V Nesplein", city: "Amsterdam", country: "Netherlands", tier: "moderate", tags: ["Nightlife", "Historical"], address: "Nes 49, 1012 KD Amsterdam, Netherlands", website: "https://www.hotelv.nl/", nearby: ["Dam Square", "Rokin", "Royal Palace"] },
  { id: "h124", name: "a&o Berlin Hauptbahnhof", city: "Berlin", country: "Germany", tier: "budget", tags: ["Historical", "Museums"], address: "Lehrter Str. 12, 10557 Berlin, Germany", website: "https://www.aohostels.com/en/berlin/berlin-hauptbahnhof/", nearby: ["Berlin Hauptbahnhof", "Reichstag", "Brandenburg Gate"] },
  { id: "h125", name: "Generator Copenhagen", city: "Copenhagen", country: "Denmark", tier: "budget", tags: ["Nightlife", "Historical"], address: "Adelgade 5-7, 1304 København, Denmark", website: "https://staygenerator.com/hostels/copenhagen", nearby: ["Nyhavn", "Rosenborg Castle", "Kongens Have"] },
  { id: "h126", name: "Czech Inn", city: "Prague", country: "Czech Republic", tier: "budget", tags: ["Nightlife", "Historical"], address: "Francouzská 76, 101 00 Praha, Czech Republic", website: "https://www.czech-inn.com/", nearby: ["Vinohrady", "Wenceslas Square", "Prague Castle"] },
  { id: "h127", name: "Condesa DF", city: "Mexico City", country: "Mexico", tier: "moderate", tags: ["Foodie", "Nightlife"], address: "Av. Veracruz 102, Condesa, 06700 Ciudad de México, Mexico", website: "https://www.condesadf.com/", nearby: ["Parque México", "Roma Norte", "Chapultepec Park"] },
  { id: "h128", name: "Belmond Mount Nelson Hotel", city: "Cape Town", country: "South Africa", tier: "luxury", tags: ["Historical", "Nature"], address: "76 Orange St, Gardens, Cape Town 8001, South Africa", website: "https://www.belmond.com/hotels/africa/south-africa/cape-town/belmond-mount-nelson-hotel/", nearby: ["Table Mountain", "Company's Garden", "Long Street"] },
];

const TIER_META = {
  budget: { label: "Budget-Friendly", emoji: "💸" },
  moderate: { label: "Moderate", emoji: "🙂" },
  luxury: { label: "Luxurious", emoji: "✨" },
};

// Trip themes for the fit-matching flow: city -> hotel -> theme -> answer.
// `tags`/`tierBoost` drive the fit score against a hotel's own tags/tier;
// `tagReasons` supplies the human-readable explanation for each match.
const THEME_META = {
  romantic: {
    label: "Romantic",
    emoji: "💕",
    blurb: "A getaway built for two",
    tierBoost: ["luxury"],
    tags: ["Beach", "Historical", "Foodie", "Nightlife"],
    tagReasons: {
      Beach: "a scenic beach backdrop for sunset walks",
      Historical: "charming historic streets perfect for romantic strolls",
      Foodie: "acclaimed restaurants nearby for a special dinner",
      Nightlife: "intimate bars and lounges for an evening out",
    },
  },
  family: {
    label: "Family",
    emoji: "👨‍👩‍👧",
    blurb: "Fun and easy for everyone",
    tierBoost: ["moderate", "budget"],
    tags: ["Beach", "Nature", "Museums", "Shopping"],
    tagReasons: {
      Beach: "an easy, safe beach for the kids",
      Nature: "outdoor space for the whole family to explore",
      Museums: "kid-friendly museums and attractions close by",
      Shopping: "family-friendly shopping nearby",
    },
  },
  business: {
    label: "Business",
    emoji: "💼",
    blurb: "Efficient and well-located",
    tierBoost: ["luxury", "moderate"],
    tags: ["Historical", "Shopping", "Foodie", "Nightlife"],
    tagReasons: {
      Historical: "centrally located in the city core",
      Shopping: "close to the main commercial district",
      Foodie: "solid options nearby for client dinners",
      Nightlife: "convenient spots to unwind after meetings",
    },
  },
  adventure: {
    label: "Adventure",
    emoji: "🧗",
    blurb: "Built around getting outside",
    tierBoost: [],
    tags: ["Nature", "Beach"],
    tagReasons: {
      Nature: "easy access to trails and the outdoors",
      Beach: "water sports and beach adventures nearby",
    },
  },
  relaxation: {
    label: "Relaxation",
    emoji: "🧘",
    blurb: "Slow down and unwind",
    tierBoost: ["luxury"],
    tags: ["Beach", "Nature"],
    tagReasons: {
      Beach: "a tranquil beachfront setting to unwind",
      Nature: "peaceful natural surroundings for total relaxation",
    },
  },
};
